const $=s=>document.querySelector(s),D=DATA,canvas=$('#game'),ctx=canvas.getContext('2d'),modal=$('#modal');let game=null,keys={},last=0,saveTimer=0,sound=false,audioCtx;let world=new SCENE.World(),dialogNpc=null,hudTimer=0,transitionUntil=0,walkPath=[];const playerLook={skin:'#d69c72',hair:'#4c302b',shirt:'#e6b451',style:0,glasses:false,accessory:0};
const desks=Array.from({length:8},(_,i)=>({x:150+(i%4)*190,y:210+Math.floor(i/4)*170,w:105,h:52}));
function save(){if(game)try{if(world.floor===game.s.floor)game.s.npcMotion=world.snapshot();localStorage.setItem('proximo-andar-v1',JSON.stringify(game.s))}catch(e){$('#lastlog').textContent='Não foi possível salvar neste navegador. Permita armazenamento local.'}}
function show(html,kind=''){keys={};walkPath=[];modal.className=kind;dialogNpc=kind==='conversation'?dialogNpc:null;$('#modalbody').innerHTML=html;if(!modal.open)modal.showModal()}
function dismissModal(){if(game?.s.activeTask){game.abortTask();save();refresh();miniResult();return}modal.close();dialogNpc=null;last=performance.now();save();refresh()}
function head(title){return '<div class="modalhead"><h2>'+title+'</h2><button onclick="dismissModal()" aria-label="Fechar">✕</button></div>'}
function button(text,action,disabled=false,primary=false){return '<button '+(primary?'class="primary" ':'')+(disabled?'disabled ':'')+'onclick="'+action+'">'+text+'</button>'}
function startScreen(){show('<small>NIMBUS TECHNOLOGIES · RPG DE ESCRITÓRIO</small><h1>Próximo Andar</h1><p class="intro">Você chegou como desenvolvedor pleno.<br>A próxima cadeira se conquista em equipe.</p><div class="startart">'+Array.from({length:7},(_,i)=>'<i style="height:'+(20+i*10)+'px"></i>').join('')+'</div><p>Explore sete andares, resolva problemas e descubra em quem confiar. Trabalho e relações contam juntos.</p><div class="actions">'+button('Nova carreira','begin(\'normal\')',false,true)+button('Continuar','resume()',!localStorage.getItem('proximo-andar-v1'))+button('Demonstração','begin(\'demo\')')+'</div><p>Normal: 12–18 dias de jogo. Demonstração: recompensas ×3, relações ×2 e sem espera mínima por cargo; roteiro de 10–15 minutos. O relógio mantém 1 segundo real = 1 minuto de jogo.</p>')}
function begin(mode){if(localStorage.getItem('proximo-andar-v1')){show(head('Começar de novo?')+'<p>Isso substituirá a carreira salva neste navegador.</p><div class="actions">'+button('Substituir e começar',"newGame('"+mode+"')",false,true)+button('Voltar','startScreen()')+'</div>');return}newGame(mode)}
function newGame(mode){game=new Game(mode);world=new SCENE.World();save();dismissModal();conversation(D.npcs[0],'Bem-vindo à Nimbus! Eu sou a Lia. Seu crachá diz desenvolvedor pleno, mas aqui você vai conhecer bem mais do que código.',[{label:'Por onde eu começo?',action:'welcomeGuide()'},{label:'Vou conhecer o escritório. Até já!',action:'dismissModal()'}],'Sua primeira manhã · dia 1, 08h');refresh()}
function welcomeGuide(){conversation(D.npcs[0],'Converse com as pessoas e escolha uma entrega no seu caderno. A Helena, no segundo andar, pode orientar você. Quando chegar a hora de crescer, vai precisar de bons resultados e de gente que confie no seu trabalho.',[{label:'Certo. Vou dar uma volta.',action:'dismissModal()'}],'WASD/setas ou clique no chão: caminhar · E: interagir · T: entregas · V: vagas · Esc: pausa. Na saída você encerra o dia.')}
function resume(){try{let s=JSON.parse(localStorage.getItem('proximo-andar-v1'));if(s.version!==1||s.relations.length!==70)throw Error();game=new Game(s.mode,s);world=new SCENE.World(game.s.npcMotion);SCENE.setFloor(game.s.floor);if(SCENE.blocked(game.s.x,game.s.y)){game.s.x=480;game.s.y=140}modal.close();refresh();if(game.s.activeTask)showMini()}catch{show(head('Save indisponível')+'<p>O salvamento não pôde ser lido. Comece uma nova carreira.</p>'+button('Nova carreira',"newGame('normal')"))}}
function act(fn){fn();save();refresh();if(game.s.victory)win()}
function refresh(){if(!game)return;const s=game.s;$('#mode').textContent=s.mode==='demo'?'DEMONSTRAÇÃO · ×3 ENTREGAS / ×2 RELAÇÕES':'CARREIRA NORMAL';$('#rank').textContent=s.receptionDuty?'Atendimento · recepção':D.roles[s.rank];$('#clock').textContent='Dia '+game.day+' · '+game.clock();$('#floorname').textContent=String(s.floor).padStart(2,'0')+' · '+D.layouts[s.floor-1].name;$('#hud').innerHTML=[['ϟ','Energia',Math.round(s.energy),100],['◷','Fadiga',Math.round(s.fatigue),100],['★','Prestígio',s.prestige.toFixed(1),100],['✓','Entregas',s.deliveries.toFixed(1),100],['◎','Influência',game.influence,85]].map(([icon,label,value,max])=>'<button class="stat" '+(label==='Influência'?'onclick="networkPanel()"':'onclick="panel(\'log\')"')+' title="'+label+'"><span class="stat-icon">'+icon+'</span><span><small>'+label+'</small><strong>'+value+'</strong><progress max="'+max+'" value="'+value+'"></progress></span></button>').join('');let missing=game.requirements().filter(r=>!r.ok);$('#objective').textContent=s.victory?'Uma Nimbus melhor.':'Rumo a '+D.roles[s.rank+1];$('#objectiveText').textContent=missing.length?'Falta: '+missing[0].label+'. Veja todos os requisitos em Vagas.':'Tudo pronto. Candidate-se no painel de Vagas.';let episode=Game.episodes.find(e=>['accepted','done'].includes(s.story.events[e.id]));if(episode){$('#objective').textContent=episode.title;$('#objectiveText').textContent=s.story.events[episode.id]==='done'?'✓ Entrega pronta · converse com '+D.npcs[episode.npc].name:episode.goal;}$('#lastlog').textContent=s.logs[0]||''}
function panel(type){if(!game)return;if(type==='relations'){networkPanel();return;}let s=game.s,html='';if(type==='tasks'){html=head('Sprint de hoje')+'<div class="workflow-strip">'+['⌕ Diagnosticar','▦ Revisar','◆ Implementar','◈ Estratégia'].map((v,i)=>'<span class="'+(game.workflow.stage>i?'done':'')+'">'+v+'</span>').join('<b>→</b>')+'</div><div class="cards tasklist">'+D.tasks.map(t=>{let reason=game.workReason(t.id);return '<div class="card"><span class="task-symbol">'+taskIcons[t.id]+'</span><span class="badge">'+(s.rank>=3?'COORDENAÇÃO':'EM EQUIPE')+' · '+t.minutes+' min base</span><h3>'+t.name+'</h3><p>'+t.desc+'</p><span class="badge">Energia −'+t.cost+' · prazo 18h</span><p class="'+(reason?'bad':'ok')+'">'+(reason||'Disponível · '+(s.memory[game.day+':task:'+t.id]||0)+'/2 feitas hoje')+'</p>'+button('Examinar situação',"taskScene('"+t.id+"')",!!reason)+'</div>'}).join('')+'</div><div class="actions">'+button('Encerrar o dia','restMenu()')+'</div>'}

if(type==='vacancies'){html=head('Painel de vagas')+'<h3>'+D.roles[Math.min(7,s.rank+1)]+'</h3><p>Vaga por crescimento e sucessão. Avaliação por requisitos publicados; ao cumpri-los, você tem prioridade. Concorrente: <b>'+['Caio Torres','Breno Dias','Otávio Sá'][s.rank%3]+'</b>. A rodada termina no dia '+s.vacancyUntil+'. '+(s.reopen?'Nova chance: dia '+s.reopen+'.':'')+' Uma derrota não retira entregas nem apoios.</p><p>Rivais ativos: '+s.rivals.map(r=>r.name+' '+r.progress+'%').join(' · ')+' (avanço limitado a 34 pontos/dia; só assumem no prazo).</p><div class="card">'+game.requirements().map(r=>'<div class="'+(r.ok?'ok':'bad')+'">'+(r.ok?'✓ ':'○ ')+r.label+'</div>').join('')+'</div><div class="actions">'+button('Candidatar-se e avaliar','apply()',game.requirements().some(r=>!r.ok)||s.rank===7,true)+'</div><p>Apoio é pedido em conversa. Conserve a relação: o limiar cresce junto com a responsabilidade. CEO também exige proposta estratégica e apoio do conselho.</p>'}
if(type==='relations'){html=head('Pessoas da Nimbus')+'<p>Influência = soma da confiança positiva × peso de cada pessoa / 30. Relações de todos os andares dão apoio, preparo e apresentações.</p><div class="cards">'+D.npcs.map(n=>'<div class="card"><b>'+n.name+'</b> · '+n.job+'<p>Andar '+n.floor+' · '+n.interest+' · '+n.context+'</p><span class="badge">Relação '+s.relations[n.id]+' · influência '+n.influence+' · '+(s.supports.includes(n.id)?'Apoio confirmado':'Sem apoio')+'</span><p>Agenda: '+Math.floor(n.start/60)+':'+String(n.start%60).padStart(2,'0')+'–'+Math.floor(n.end/60)+'h'+(n.extra?' (faz extras)':'')+(n.floor>=6?' · café na recepção 12h–13h30':'')+'. '+(game.location(n)?'Presente no andar '+game.location(n):'Fora do escritório')+'</p></div>').join('')+'</div>'}
if(type==='agenda'){html=head('Agenda do dia')+'<p>Expediente 08h–18h. Pessoas com extras ficam até 20h. Executivos visitam a recepção ao meio-dia. Compromissos têm tolerância de 45 minutos.</p>'+s.appointments.map((a,i)=>'<div class="card">Café com '+D.npcs[a.id].name+' · dia '+(Math.floor(a.at/1440)+1)+' '+Math.floor(a.at%1440/60)+':'+String(Math.floor(a.at%60)).padStart(2,'0')+'<div class="actions">'+button(a.done?'Encerrado':'Participar',"attend("+i+")",a.done||s.time<a.at||s.time>a.at+45)+'</div></div>').join('')+'<div class="actions">'+button('Esperar 15 min','waitTime()')+'</div>'}
if(type==='log')html=head('Registro de consequências')+s.logs.map(l=>'<div class="logline">'+l+'</div>').join('');show(html)}
function conversation(n,text,choices,feedback=''){dialogNpc=n.id;let friendship=game?.s.relations[n.id]||0,friendLabel=friendship<0?'Relação tensa':friendship<12?'Conhecendo você':friendship<24?'Confiança crescendo':'Amizade construída';show('<div class="conversation-inner"><div class="portrait-frame"><canvas id="portrait" width="160" height="180" aria-label="Retrato de '+n.name+'"></canvas><span>'+n.name+'</span></div><div class="speech"><div class="speaker"><div><small>'+n.job+'</small><h2>'+n.name+'</h2></div><button onclick="dismissModal()" aria-label="Encerrar conversa">✕</button></div><div class="dialog-friendship"><div><span>♡ Amizade · '+friendLabel+'</span><strong>'+friendship+'/100</strong></div><meter min="0" max="100" value="'+Math.max(0,friendship)+'" aria-label="Amizade com '+n.name+'" aria-valuetext="'+friendship+' de 100; '+friendLabel+'"></meter></div><p class="spoken">'+text+'</p>'+(feedback?'<p class="consequence">'+feedback+'</p>':'')+'<div class="choices">'+choices.map((c,i)=>button('<kbd>'+(i+1)+'</kbd> '+c.label,c.action,c.disabled)).join('')+'</div><small class="dialog-help">1–4 escolher · Esc sair · tempo pausado</small></div></div>','conversation');SCENE.portrait($('#portrait'),game.npcView?game.npcView(n):n)}
function taskScene(id){const t=D.tasks.find(t=>t.id===id),scene=D.taskScenes[id],n=D.npcs[[14,14,0,30,42,66][D.tasks.indexOf(t)]];conversation(n,scene.intro,['segura','colaborativa','rápida'].map((a,i)=>({label:scene.choices[i]+' <span class="choice-cost">'+Math.round(t.minutes*(a==='rápida'?.7:a==='colaborativa'?1.1:1))+' min</span>',action:"doWork('"+id+"','"+a+"')"})), 'Energia −'+t.cost+' · prazo 18h · recompensa base '+t.points*game.cfg.reward+' entregas e '+t.prestige*game.cfg.reward+' prestígio. '+(game.s.prepared?'Você tem orientação: +15% de qualidade.':'Concluir o minigame é necessário. Falhar ou sair consome o esforço, sem recompensa.')+(game.hour>=1080?' Hora extra: mais fadiga e prazo excedido.':''))}
function doWork(id,a){let reason=game.workReason(id);if(reason){show(head('Agora não é possível')+'<p>'+reason+'</p>'+button('Voltar às demandas',"panel('tasks')"));return}if(game.startTask(id,a)){save();refresh();showMini()}}
function apply(){act(()=>game.promote());if(!game.s.victory)show(head('Novo cargo!')+'<h2>'+D.roles[game.s.rank]+'</h2><p>'+game.s.logs[0]+'</p>'+button('Continuar','dismissModal()',false,true))}
function attend(i){let a=game.s.appointments[i],p=a&&world.people.get(a.id);if(!p||!p.arrived||!p.coffee||Math.hypot(p.x-game.s.x,p.y-game.s.y)>70){show(head('Encontre seu colega')+'<p>Vá até a máquina de café do andar '+(a?.floor||D.npcs[a.id].floor)+' e aproxime-se de '+D.npcs[a.id].name+'. O encontro acontece lá.</p>'+button('Voltar ao escritório','dismissModal()'));return}act(()=>game.attend(i));panel('agenda')}function waitTime(){act(()=>game.advance(15));panel('agenda')}
function talk(id){let episode=game.storyOffer(id);if(episode&&!game.s.story.events[episode.id]||episode&&game.s.story.events[episode.id]==='done'){storyConversation(episode);return}let n=D.npcs[id],r=game.s.relations[id],stage=r<12?0:r<24?1:2;let text=n.central?n.events[stage]:['Ainda estou pegando o ritmo de hoje. Você também está com bastante coisa para fazer?','Bom te ver de novo. Aquela ajuda fez diferença para mim.','Senta aqui um minuto. Quero saber como anda sua próxima entrega.'][stage];let met=Object.keys(game.s.memory).some(k=>k.includes(':'+id+':'));if(met&&stage===0)text='Você voltou! Eu estava pensando no que conversamos. '+(n.central?n.events[0]:'Vamos encontrar um tempo para conversar com calma?');text=game.storyText(id)||text;conversation(n,text,[{label:'Como anda seu interesse por '+n.interest+'?',action:"dialogAction("+id+",'listen')"},{label:'Posso ajudar com alguma coisa?',action:"dialogAction("+id+",'help')"},{label:'Queria ouvir sua opinião sobre minha entrega.',action:"dialogAction("+id+",'advice')"},{label:'Tem outra coisa que queria conversar…',action:'moreTalk('+id+')'}],(world.people.get(id)?.activity||'no escritório')+' · '+(game.s.supports.includes(id)?'Apoia sua candidatura':r>=20?'Confiança construída':r>0?'Conhecendo você':'Primeira aproximação'))}
function moreTalk(id){const n=D.npcs[id];conversation(n,'Pode falar. O que você tem em mente?',[{label:'Quero compartilhar os resultados da equipe.',action:"dialogAction("+id+",'share')"},{label:'Você apoiaria minha candidatura?',action:"dialogAction("+id+",'support')"},{label:'Vamos tomar um café daqui a uma hora?',action:"dialogAction("+id+",'coffee')"},{label:'Preciso esclarecer a autoria daquela entrega.',action:"dialogAction("+id+",'defend')"}], 'Apoio requer relação '+(8+n.floor*2)+' e '+n.floor*2+' entregas. Você tem '+game.s.relations[id]+' de relação. Pedir cedo pode prejudicar a confiança.')}
function dialogAction(id,a){const n=D.npcs[id],before=game.s.relations[id],supported=game.s.supports.includes(id),evidence=game.s.evidence;let used=game.talk(id,a);save();refresh();let delta=game.s.relations[id]-before,reply='';if(!used)reply=!game.location(n)?'Meu expediente terminou. Vamos conversar amanhã?':'A gente já conversou sobre isso hoje. Vamos retomar depois de algo novo acontecer?';else if(a==='listen')reply={café:'Descobri uma mistura nova. Um dia trago para a equipe experimentar.',livros:'Estou lendo um livro que me fez repensar como escuto as pessoas.',música:'Tenho uma playlist para os dias difíceis. Posso te mostrar no intervalo.',jardinagem:'Minha planta finalmente deu uma folha nova. Paciência faz diferença.',corrida:'Hoje consegui correr antes do trabalho. Ajuda a organizar as ideias.',cinema:'Vi um filme que ficou na minha cabeça. Quero discutir o final com alguém.',jogos:'Gosto quando um jogo me deixa resolver as coisas do meu jeito.',sustentabilidade:'Quero que nossas escolhas durem mais do que o próximo trimestre.'}[n.interest]+' E você, consegue desligar um pouco?';else if(a==='help')reply=n.personality==='hostil'?'Tudo bem. Vamos registrar quem fez o quê antes de começar.':'Sim. Preciso de uma segunda opinião. Obrigado por reservar esse tempo — vou lembrar de dividir o crédito.';else if(a==='advice')reply='Escolha um problema pequeno, entenda a causa e peça revisão antes de entregar. Você não precisa provar tudo sozinho.';else if(a==='share')reply=delta>0?'Você trouxe resultados e reconheceu quem participou. É esse tipo de trabalho que eu quero ver crescer.':'Ainda preciso ver algo concreto. Volte com uma entrega e a gente conversa melhor.';else if(a==='support')reply=game.s.supports.includes(id)?'Sim. Você pode contar comigo na avaliação. Também vou apresentar você às pessoas do próximo andar.':'Ainda não consigo assumir esse compromisso. Vamos trabalhar juntos um pouco mais antes?';else if(a==='coffee')reply='Combinado. Daqui a uma hora! Anote na agenda para não passar batido.';else if(a==='defend')reply=evidence?'O registro deixa claro quem participou. Vou ajudar a esclarecer isso.':'Sem um registro, eu não consigo confirmar essa história. Vamos procurar evidências primeiro.';conversation(n,reply,[{label:'Quero te perguntar mais uma coisa.',action:'talk('+id+')'},{label:'Obrigado. Nos vemos pelo escritório.',action:'dismissModal()'}],used?'Relação '+(delta>=0?'+':'')+delta+' · '+(a==='help'?'30 minutos dedicados à ajuda.':a==='advice'?'Próxima entrega preparada.':'15 minutos de conversa.'):'Sem custo de tempo ou ganho repetido.')}
function elevator(){show(head('Qual é o próximo andar?')+'<div class="elevator-grid">'+D.layouts.map((l,i)=>button('<b class="floor-number">0'+(i+1)+'</b><span>'+l.name+'<small>'+l.feature+'</small><small>'+(game.access(i+1)?'⌑ Acesso liberado':'◎ '+D.influenceAccess[i]+' influência · ou cargo/convite')+'</small></span>','travel('+(i+1)+')',!game.access(i+1))).join('')+'</div>')}
function travel(f){act(()=>game.go(f));world=new SCENE.World();transitionUntil=performance.now()+450;dismissModal()}
function restMenu(){show(head('Por hoje, é isso.')+'<p class="intro">Amanhã tem mais. Escolha quanto vai dormir; se acordar antes da abertura, o tempo pessoal passa até as 8h.</p><p>Você recupera apenas pelas horas dormidas. Menos de 7h acumula fadiga. Entregas encerram às 20h.</p><label for="hours">Horas de sono</label> <select id="hours">'+[2,4,6,8,10].map(h=>'<option '+(h===8?'selected':'')+'>'+h+'</option>').join('')+'</select><div class="actions">'+button('Dormir e retornar no horário útil','sleepChosen()',false,true)+button('Ainda tenho algo para fazer','dismissModal()')+'</div>')}
function sleepChosen(){act(()=>game.endDay(Number($('#hours').value)));world=new SCENE.World();transitionUntil=performance.now()+600;dismissModal();show(head('Um novo expediente')+'<p class="intro">Dia '+game.day+' · '+game.clock()+'. As portas da Nimbus estão abertas.</p><p>Energia '+Math.round(game.s.energy)+' · fadiga '+Math.round(game.s.fatigue)+'. '+(game.s.fatigue>60?'Hoje vale reduzir o ritmo e buscar orientação.':'Procure sua equipe e escolha a prioridade do dia.')+'</p>'+button('Entrar','dismissModal()',false,true))}
function sleepMorning(){sleepChosen()}
function closedOffice(){show(head('O expediente terminou')+'<p>As equipes voltam às 8h. Você pode dormir para recuperar energia ou apenas avançar até a abertura, sem recuperação adicional.</p><div class="actions">'+button('Encerrar o dia e descansar','restMenu()',false,true)+button('Aguardar a abertura','waitOpening()')+'</div>')}
function waitOpening(){act(()=>{game.advance(game.hour<480?480-game.hour:1440-game.hour+480);game.log('As portas abriram. Esperar não recuperou sono nem energia.');});world=new SCENE.World();dismissModal()}
function pause(){if(!game)return;if(modal.open){dismissModal();return}show(head('Pausa')+'<p>Tempo parado. Seu progresso é salvo automaticamente após ações e a cada 10 segundos.</p><div class="actions">'+button('Retomar','dismissModal()',false,true)+button('Descansar / sair','restMenu()')+button('Menu inicial','save();startScreen()')+'</div>')}
function win(){show(head('Você chegou à presidência')+'<h1>O próximo andar é coletivo.</h1><p>CEO da Nimbus Technologies — dia '+game.day+'.</p><div class="card">'+game.s.deliveries.toFixed(1)+' entregas · '+game.s.prestige.toFixed(1)+' prestígio<br>'+game.s.supports.length+' apoios · influência '+game.influence+'<br>'+game.s.losses+' rodadas superadas após derrota.</div><p>Seu plano combina resultados, pessoas e sustentabilidade. Quem abriu portas continua fazendo parte da história.</p>'+button('Voltar ao escritório','dismissModal()',false,true))}
function npcPos(n){return world.people.get(n.id)||SCENE.home(n)}
function near(){if(!game)return null;let {x,y}=game.s;if(Math.hypot(x-480,y-85)<85)return {type:'elevator',label:'E · Elevador'};if(y>515&&Math.abs(x-480)<115)return {type:'exit',label:'E · Encerrar o dia'};let closest=null,distance=54;for(let n of D.npcs){if(game.location(n)===game.s.floor){let p=world.people.get(n.id);if(!p)continue;let d=Math.hypot(x-p.x,y-p.y);if(d<distance){distance=d;closest={type:'npc',id:n.id,label:'E · '+n.name+' · '+(p.activity||'no escritório')}}}}if(closest){if(game.s.floor===3&&game.hour>=900&&game.hour<945&&[15,31].includes(closest.id))return {type:'plot',label:'E · Ouvir conversa'};return closest;}let object=D.layouts[game.s.floor-1].objects.find(o=>!['plant','garden'].includes(o.type)&&x>o.x-55&&x<o.x+o.w+55&&y>o.y-55&&y<o.y+o.h+55);if(object)return {type:object.type==='coffee'||object.type==='sofa'?'coffee':object.type==='desk'||object.type==='executive'?'desk':'room',object,label:'E · '+object.label};return null}
function interact(){if(!game||modal.open)return;let n=near();if(!n)return;if(n.type==='elevator')elevator();if(n.type==='exit')restMenu();if(n.type==='npc')talk(n.id);if(n.type==='desk')panel('tasks');if(n.type==='coffee')coffeeMenu();if(n.type==='room')roomMenu(n.object);if(n.type==='plot')plotMenu()}
function blocked(x,y){return SCENE.blocked(x,y,game?game.s.floor:2)}
function draw(){let floor=game?game.s.floor:1;ctx.imageSmoothingEnabled=true;SCENE.background(ctx,floor,game?game.hour:600);if(game){world.update(game,0,dialogNpc);let target=near();let list=[...world.people.values()].map(p=>({...p,n:D.npcs[p.id]}));list.push({...game.s,player:true});
// Sentado só conta perto de mobília com cadeira a sério (secretária/balcão) — nunca ao acaso, parado no meio do chão.
let deskFurniture=D.layouts[floor-1].objects.filter(o=>['desk','executive','console','reception'].includes(o.type));
list.sort((a,b)=>a.y-b.y).forEach(p=>{let active=p.player||target?.id===p.id;let deskHere=p.player||p.moving||!p.arrived||p.coffee||p.partner?null:deskFurniture.find(o=>p.x>o.x-25&&p.x<o.x+o.w+25&&p.y>o.y-25&&p.y<o.y+o.h+55);let seated=!!deskHere,chair=seated?SCENE.chairSpot(deskHere):null,drawX=chair?chair.x:p.x,drawY=chair?chair.y:p.y;SCENE.sprite(ctx,drawX,drawY,p.player?playerLook:p.n.appearance,p.facing,p.stride,p.moving,active,seated);if(active&&!p.player){ctx.font='bold 13px system-ui';ctx.textAlign='center';let label=p.n.name;ctx.fillStyle='#203744';ctx.fillRect(p.x-75,p.y-61,150,20);ctx.fillStyle='#fff0c5';ctx.fillText(label,p.x,p.y-46)}if(!p.player&&p.chat&&!active){SCENE.round(ctx,p.x-65,p.y-66,130,20,7,'#fff5db');SCENE.text(ctx,p.chat,p.x,p.y-52,10);}else if(!p.player&&game.storyOffer(p.id)&&!['accepted'].includes(game.s.story.events[game.storyOffer(p.id).id])){SCENE.round(ctx,p.x-9,p.y-42,18,20,7,'#ffe1a0');SCENE.text(ctx,'!',p.x,p.y-27,15);}if(p.player){ctx.fillStyle='#fff0a4';ctx.beginPath();ctx.moveTo(p.x,p.y-43);ctx.lineTo(p.x-4,p.y-49);ctx.lineTo(p.x+4,p.y-49);ctx.fill()}});$('#hint').textContent=target?.label||(game.hour>=1080?'Horas extras · entregas até 20h. E na saída para encerrar.':'Clique ou WASD / setas · E interagir · ◎ sua rede abre portas');if(transitionUntil>performance.now()){ctx.fillStyle='rgba(20,34,46,'+Math.min(.8,(transitionUntil-performance.now())/600)+')';ctx.fillRect(0,0,960,600)}}}
function frame(t){let dt=Math.min(Math.max((t-last)/1000,0),.05);last=t;if(game&&!modal.open&&!document.hidden){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy)walkPath=[];if(!dx&&!dy&&walkPath.length){let p=walkPath[0],dist=Math.hypot(p.x-game.s.x,p.y-game.s.y);if(dist<3)walkPath.shift();else{dx=p.x-game.s.x;dy=p.y-game.s.y;dt=Math.min(dt,dist/D.balance.moveSpeed)}}SCENE.move(game.s,dx,dy,dt,D.balance.moveSpeed,[...world.people.values()]);game.advance(dt);world.update(game,dt);storyTick();saveTimer+=dt;hudTimer+=dt;if(saveTimer>D.balance.saveInterval){save();saveTimer=0}if(hudTimer>.25){refresh();hudTimer=0}if(game.hour<480||game.hour>=1200)closedOffice();}else if(game)game.s.moving=false;draw();requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.repeat)return;if(e.key==='Escape'){e.preventDefault();pause();return}if(modal.open){if(modal.className==='conversation'&&/^[1-4]$/.test(e.key)){let choice=document.querySelectorAll('.choices button')[Number(e.key)-1];if(choice&&!choice.disabled)choice.click()}return}keys[e.key.length===1?e.key.toLowerCase():e.key]=true;if(e.key.toLowerCase()==='e')interact();let p={t:'tasks',v:'vacancies',g:'agenda',r:'relations'}[e.key.toLowerCase()];if(p)panel(p)});window.addEventListener('keyup',e=>keys[e.key.length===1?e.key.toLowerCase():e.key]=false);window.addEventListener('blur',()=>{keys={};save()});document.addEventListener('visibilitychange',()=>{keys={};last=performance.now();save()});modal.addEventListener('cancel',e=>{e.preventDefault();if(game)dismissModal()});document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>panel(b.dataset.panel));document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys[b.dataset.move]=true;b.setPointerCapture(e.pointerId)};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.move]=false});$('#pause').onclick=pause;$('#interact').onclick=interact;$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='Som: '+(sound?'ligado':'desligado');if(sound){audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=440;g.gain.setValueAtTime(.04,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.4);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.4)}};canvas.addEventListener('click',e=>{if(!game||modal.open)return;const bounds=canvas.getBoundingClientRect();let target={x:(e.clientX-bounds.left)*960/bounds.width,y:(e.clientY-bounds.top)*600/bounds.height};if(!blocked(target.x,target.y))walkPath=SCENE.path(game.s,target);});startScreen();requestAnimationFrame(frame);

// Optional browser-native tools: normal UI actions, no hidden rewards or debug state.
if(navigator.modelContext?.registerTool){for(const [name,description,type] of [['consultar_vagas','Abrir requisitos públicos da próxima promoção.','vacancies'],['consultar_tarefas','Abrir demandas e escolhas disponíveis.','tasks'],['consultar_agenda','Abrir compromissos e expediente.','agenda']])navigator.modelContext.registerTool({name,description,inputSchema:{type:'object',properties:{}},execute:async()=>{if(!game)return {content:[{type:'text',text:'Comece uma carreira no menu.'}]};panel(type);return {content:[{type:'text',text:'Painel aberto. O tempo está pausado.'}]}}})}

function storyConversation(e){let done=game.s.story.events[e.id]==='done';game.s.story.presented[e.id+':'+(done?'done':'offer')]=true;conversation(D.npcs[e.npc],done?e.end:e.intro,done?[{label:'Fico feliz que tenha dado certo.',action:"storyDecision('"+e.id+"','accept')"}]:[{label:'Pode contar comigo.',action:"storyDecision('"+e.id+"','accept')"},{label:'Hoje não consigo. Falamos amanhã?',action:"storyDecision('"+e.id+"','later')"},{label:'Prefiro não assumir isso.',action:"storyDecision('"+e.id+"','decline')"}],e.title+(done?' · Alívio':' · Preocupação'));save()}
function storyDecision(id,choice){game.storyChoose(id,choice);dismissModal()}
function storyTick(){if(modal.open)return;let e=game.storyOffer();if(!e)return;let state=game.s.story.events[e.id];if(state==='accepted')return;let key=e.id+':'+(state==='done'?'done':'offer');let p=world.people.get(e.npc);if(p&&!game.s.story.presented[key]&&Math.hypot(p.x-game.s.x,p.y-game.s.y)<65)storyConversation(e)}
