const legacyPanel=panel,legacyRoom=roomMenu,legacyTalk=talk,legacyInteract=interact,legacyDialogAction=dialogAction;
panel=function(type){if(type!=='tasks')return legacyPanel(type);show(head('Ciclo de '+D.roles[game.s.rank])+'<div class="workflow-strip">'+game.tasks.map(t=>'<span class="'+(game.workflow.stage>t.step?'done':'')+'">'+(game.workflow.stage>t.step?'✓ ':'')+t.name+'</span>').join('<b>→</b>')+'</div><div class="cards">'+game.tasks.map(t=>'<div class="card"><h3>'+t.name+'</h3><p>'+t.desc+'</p><p>Andar '+t.floor+' · '+game.taskPlace(t).label+'</p>'+button('Mostrar destino',"taskDestination('"+t.id+"')")+(game.atTask(t)?button('Examinar atividade',"taskScene('"+t.id+"')"):'')+'</div>').join('')+'</div>')};
function taskDestination(id){let t=game.tasks.find(t=>t.id===id);show(head(t.name)+'<p>Vá ao andar '+t.floor+', aproxime-se de '+game.taskPlace(t).label+' e pressione E.</p>'+(t.participants.length?'<p>Convide pessoalmente: '+t.participants.map(id=>D.npcs[id].name+' ('+D.npcs[id].job+')').join(', ')+'. Eles chegam à sala dez minutos após o último convite.</p>':'')+button('Voltar ao escritório','dismissModal()'))}
taskScene=function(id){let t=game.tasks.find(t=>t.id===id);if(!t)return;show(head(t.name)+'<p>'+t.desc+'</p>'+['rápida','segura','colaborativa'].map((a,i)=>{let e=game.effort(a),reason=game.workReason(id,a);return '<div class="card"><h3>'+['Essencial · puzzle simples','Completa · puzzle intermediário','Aprofundada · puzzle difícil'][i]+'</h3><p>'+Math.round(t.minutes*e.factor)+' min · energia −'+Math.ceil(t.cost*e.cost)+' · prestígio base '+(t.prestige*e.reward).toFixed(1)+'</p><p>'+reason+'</p>'+button('Escolher',"doWork('"+id+"','"+a+"')",!!reason)+'</div>'}).join(''))};
doWork=function(id,a){if(game.startTask(id,a)){save();refresh();showMini()}else taskScene(id)};
roomMenu=function(o){let local=game.tasks.filter(t=>t.floor===game.s.floor&&game.taskPlace(t).id===o.id);if(!local.length)return legacyRoom(o);show(head(o.label)+'<div class="actions">'+local.map(t=>button(t.name,"taskScene('"+t.id+"')")).join('')+'</div>')};
interact=function(){if(!game||modal.open)return;let t=game.tasks.find(t=>t.step===Math.min(game.workflow.stage,3)&&game.atTask(t));if(t){taskScene(t.id);return}let target=near();if(target?.type==='desk'){let o=D.layouts[game.s.floor-1].objects.find(o=>game.s.x>o.x-65&&game.s.x<o.x+o.w+65&&game.s.y>o.y-65&&game.s.y<o.y+o.h+65);if(o){roomMenu(o);return}}legacyInteract()};
talk=function(id){let t=game.tasks.find(t=>t.participants.includes(id));let e=game.storyOffer(id);if(e&&(!game.s.story.events[e.id]||game.s.story.events[e.id]==='done'))return legacyTalk(id);let n=D.npcs[id];conversation(n,game.storyText(id)||game.personalLine(id),[{label:'Como começou essa história?',action:'personalConversation('+id+')'},{label:'Vamos falar de trabalho.',action:'workConversation('+id+')'},...(t?[{label:'Quero te convidar: '+t.name,action:"inviteColleague('"+t.id+"',"+id+")"}]:[]),{label:'Até mais!',action:'dismissModal()'}],n.background)};
function workConversation(id){legacyTalk(id)}
function personalConversation(id){let n=D.npcs[id];game.talk(id,'listen');save();refresh();conversation(n,game.personalLine(id),[{label:'Obrigado por me contar.',action:'dismissModal()'},{label:'Falando de trabalho…',action:'workConversation('+id+')'}],n.background)}
function inviteColleague(task,id){let p=world.people.get(id);if(!p||Math.hypot(p.x-game.s.x,p.y-game.s.y)>70){conversation(D.npcs[id],'Me encontra no escritório para combinarmos.',[{label:'Até já.',action:'dismissModal()'}]);return}game.inviteMeeting(task,id);save();conversation(D.npcs[id],'Combinado. Vou encontrar o grupo na sala. Pode convidar os outros; chegamos em dez minutos.',[{label:'Até lá.',action:'dismissModal()'}]);}
const careerStart=game?.s.rank;
