(function(root){
function install(Game,D){
if(Game.careersInstalled)return;Game.careersInstalled=true;
const tracks=[
 ['Diagnosticar acesso','Revisar correção','Entregar funcionalidade','Demonstrar à equipe'],
 ['Investigar falha sistêmica','Revisar arquitetura','Conduzir migração','Validar operação'],
 ['Priorizar impedimentos','Orientar desenvolvedor','Planejar integração','Alinhar com produto'],
 ['Ouvir a equipe','Planejar capacidade','Negociar prazo','Conduzir retrospectiva'],
 ['Avaliar portfólio','Revisar riscos','Distribuir investimento','Comitê de diretores'],
 ['Comparar mercados','Planejar sucessão','Negociar expansão','Alinhar vice-presidências'],
 ['Auditar risco tecnológico','Definir arquitetura corporativa','Planejar investimento tecnológico','Proposta estratégica'],
 ['Ouvir conselho e clientes','Definir prioridades anuais','Negociar orçamento corporativo','Reunião de estratégia da presidência']
];
const floors=[2,3,4,4,5,6,6,7], sponsors=[2,3,4,5,6,7,7,7];
const casts=[[14],[30],[42,43],[42,43],[52,53],[60,61],[52,60,67],[52,60,66]];
// Titles in this simulation distinguish executives needed at formal meetings.
D.npcs[60].job='CTO em transição';D.npcs[67].job='CEO em sucessão';
const personal=[
 [0,'Cria dois gatos resgatados, Planilha e Anexo. Antes da Nimbus, organizava uma feira de adoção.','O Planilha dormiu em cima do formulário de adoção. Pela primeira vez, uma planilha impediu uma burocracia.','O Anexo sumiu por dez minutos. Estava dentro da caixa que eu tinha etiquetado “gato não entra”.','Brinco com isso, mas tenho medo de não achar uma casa boa para os filhotes. Obrigada por perguntar.'],
 [1,'Foi radialista de bairro e guarda vinhetas para anunciar pequenas vitórias.','Gravei uma vinheta para avisar que o café ficou pronto. O financeiro pediu uma versão de três segundos.','A Lia proibiu minha abertura de doze minutos. Disse que o café esfria antes do refrão.','A rádio fechou. Acho que ainda tento provar que minha voz faz falta.'],
 [2,'Negocia contratos de papel e material de escritório há oito anos; conhece o preço justo de cada fornecedor da cidade.','Consegui um desconto na resma A4. O segredo é nunca aceitar a primeira proposta.','O fornecedor atrasou a entrega de novo. Vou ligar antes que alguém perceba e vire piada no café.','Comecei regateando hortaliças na feira do meu bairro. Papel ou verdura, a conversa é a mesma.'],
 [3,'Concilia notas fiscais e cobra reembolsos com uma paciência que ninguém entende de onde vem.','Encontrei uma nota duplicada de duzentos reais. Ninguém comemora isso comigo, mas devia.','Perguntaram se dava para “ajeitar” um recibo. Expliquei, outra vez, por que não.','Meu pai era caixa de mercado. Aprendi cedo que um centavo errado também é um erro.'],
 [4,'Faz a ronda no fim da tarde e conhece os hábitos de cada andar melhor do que qualquer relatório.','Vi a luz do sexto andar acesa até tarde outra vez. Alguém devia mandar essas pessoas para casa.','Encontrei um crachá esquecido na recepção. Vou devolver antes que virem motivo de piada.','Trabalhei numa portaria residencial antes disso. Prefiro aqui: pelo menos ninguém esconde visita.'],
 [14,'Consertava brinquedos com o avô. Coleciona robôs de corda que nunca andam em linha reta.','Meu robô foi parar debaixo do armário. Chamei de exploração autônoma para não admitir o defeito.','O Caio colocou uma placa de “vaga reservada” para o robô. Pela primeira vez, a piada dele ajudou.','Meu avô me ensinou a consertar sem jogar fora. Talvez por isso eu insista tanto nas pessoas.'],
 [15,'Mestre de RPG aos domingos; escreve discursos épicos para personagens secundários.','Meu vendedor de batatas ganhou um monólogo de oito páginas. O grupo só queria saber o preço.','A Helena pediu meu relatório em uma página. Contei como derrota para o império da concisão.','No RPG eu sei o que acontece depois. Aqui, fico com medo de virar figurante.'],
 [30,'Cuida de um terrário e registra o crescimento do musgo como se fosse um serviço crítico.','O musgo cresceu dois milímetros. É meu único projeto sem mudança de escopo.','Breno colocou uma bandeirinha no terrário. O musgo agora tem patrocinador, aparentemente.','Depois de tantos plantões, cuidar de uma coisa silenciosa me faz bem.'],
 [31,'Corredor amador que coleciona medalhas de provas em que quase chegou atrasado.','Ganhei uma medalha por cinco quilômetros. Corri seis procurando a largada.','A Iara mediu minha rota. Eu estava dando voltas no estacionamento.','Meu pai guarda todas as medalhas. Não tenho coragem de dizer que são de participação.'],
 [42,'Já teve uma padaria e tenta acertar pão de fermentação natural nos fins de semana.','Meu fermento tem nome, agenda e mais estabilidade que o cronograma.','A Nina disse que meu pão serve de peso de porta. Reservou dois.','Fechar a padaria doeu. Quando alguém fala em cortar equipe, lembro de cada pessoa de lá.'],
 [43,'Faz curtas de terror com objetos domésticos; sua estrela é uma torradeira.','Minha torradeira ganhou um prêmio no festival da família. Concorria com o aspirador.','O Marcos emprestou um pão para o filme. Ficou assustador sem efeitos especiais.','Quero dirigir algo de verdade um dia. Por enquanto, aprender a ouvir aqui já ajuda.'],
 [52,'Coleciona mapas de cidades que visita de bicicleta e sempre erra o caminho.','Achei um atalho. Acrescentou quarenta minutos, mas tinha uma árvore ótima.','Otávio pediu meu mapa. Escrevi “não é uma recomendação de rota”.','Aprendi a pedalar adulta. Ainda gosto de lembrar que posso começar mal e melhorar.'],
 [53,'Monta maquetes ferroviárias e discute pontualidade com trens de seis centímetros.','Meu trem atrasou. O culpado foi um gato que nem mora comigo.','Clara sugeriu ciclovia na maquete. Agora tenho uma disputa de orçamento em escala.','Meu filho constrói as estações. Só deixo o trem devagar para ele conseguir acompanhar.'],
 [60,'Toca baixo numa banda que ensaia mais nomes do que músicas.','Mudamos o nome da banda de novo. Já temos material para um álbum de logotipos.','Eva sugeriu “Reunião que podia ser um solo”. Infelizmente, ficou bom.','Tocar me lembra como é difícil aprender sem fingir que já sei.'],
 [61,'Cultiva pimentas e organiza degustações voluntárias com rótulos exageradamente precisos.','Esta pimenta se chama “reunião de orçamento”. Você entende o nome alguns segundos depois.','Davi pediu uma sem ardência. Dei um tomate e preservei a amizade.','Minha mãe começou essa horta. Dividir as mudas é meu jeito de mantê-la por perto.'],
 [66,'Recupera móveis encontrados na rua e conhece a história de cada cadeira da sua casa.','Resgatei uma cadeira. Meu marido perguntou se vamos adotar a mesa também.','Artur sentou na cadeira antes de a cola secar. Agora pede relatório de estabilidade.','Gosto de coisas que ainda têm uso quando alguém já desistiu delas. Vale para empresas também.'],
 [67,'Faz teatro amador, mas só consegue decorar falas andando pela cozinha.','Decorei Shakespeare. Na reunião, só lembrei “quem terminou o leite?”.','Sofia prometeu assistir à peça. Agora estou mais nervoso do que na assembleia.','Sair da presidência me assusta. No teatro, aprendo que o espetáculo continua depois da minha cena.']
];
for(const [id,bio,...lines] of personal)Object.assign(D.npcs[id],{background:bio,personalLines:lines});
const hobbies=['restaura rádios','faz origami de animais','fotografa portas antigas','cozinha receitas da avó','joga xadrez por correspondência','cuida de uma horta comunitária','conserta bicicletas'];
for(const n of D.npcs)if(!n.background){let hobby=hobbies[n.id%hobbies.length],old=['biblioteca','loja de bairro','oficina','escola'][n.id%4];n.background='Antes da Nimbus, '+n.name+' trabalhou numa '+old+'. Hoje '+hobby+' e guarda um caderno de ideias para compartilhar com a equipe.';n.personalLines=['No intervalo eu '+hobby+'. Esta semana, transformei um pequeno erro numa história enorme.','Trouxe meu caderno. '+D.npcs[(n.id+1)%70].name+' sugeriu uma ideia que quero experimentar.','Nem sempre consegui tempo para isso. Ter alguém que se interessa já faz diferença.'];}
Object.defineProperty(Game.prototype,'tasks',{configurable:true,get(){const rank=this.s.rank;return tracks[rank].map((name,i)=>({id:rank===0?['bug','review','feature','demo'][i]:rank===6&&i===3?'strategy':'r'+rank+'s'+i,name,step:i,mini:rank===0?['bug','review','feature','mentor'][i]:['incident','review','feature','strategy'][i],floor:floors[rank],objectType:i===0?'board':i===3?'meeting':rank<2?'desk':i===1?'board':'executive',participants:i===3?casts[rank]:[],minutes:[40,45,65,75][i],cost:[7,9,12,14][i],points:2+i,prestige:2+i,desc:['Analise o contexto e escolha a prioridade.','Compare evidências antes de decidir.','Construa a proposta que será discutida.','Reúna os responsáveis e confirme os compromissos.'][i],best:'colaborativa',min:rank}));}});
Game.prototype.taskPlace=function(t){let objects=D.layouts[t.floor-1].objects;return objects.find(o=>o.type===t.objectType)||objects.find(o=>['meeting','boardtable','desk','executive'].includes(o.type))||objects[0]};
Game.prototype.atTask=function(t){let o=this.taskPlace(t);return this.s.floor===t.floor&&this.s.x>=o.x-65&&this.s.x<=o.x+o.w+65&&this.s.y>=o.y-65&&this.s.y<=o.y+o.h+65};
Game.prototype.effort=function(a){return a==='rápida'?{difficulty:1,factor:.65,reward:.7,cost:.7}:a==='colaborativa'?{difficulty:3,factor:1.3,reward:1.5,cost:1.3}:{difficulty:2,factor:1,reward:1,cost:1}};
Game.prototype.workReason=function(id,approach='segura'){let t=this.tasks.find(t=>t.id===id);if(this.s.activeTask)return 'Conclua a atividade em andamento.';if(!t)return 'Esta atividade não pertence ao seu cargo atual.';if(this.hour<480||this.hour>=1200)return 'Escritório fechado. Retorne às 8h.';if(this.workflow.stage<t.step)return 'Primeiro: '+this.tasks[t.step-1].name+'.';let e=this.effort(approach);if(this.s.energy<Math.ceil(t.cost*e.cost))return 'Energia insuficiente. Faça uma pausa.';if(this.hour+Math.round(t.minutes*e.factor)>1200)return 'Não há tempo útil suficiente hoje.';if((this.s.memory[this.day+':task:'+id]||0)>=2)return 'Tentativas de hoje encerradas.';if(!this.atTask(t))return 'Vá ao andar '+t.floor+' · '+this.taskPlace(t).label+'.';if(t.participants.length){let m=this.s.meeting;if(!m||m.id!==id||m.day!==this.day)return 'Convide os participantes pessoalmente.';if(t.participants.some(n=>!m.invited.includes(n)))return 'Ainda faltam convidados.';if(this.s.time<m.readyAt)return 'A equipe está a caminho da sala.';if(t.participants.some(id=>!m.present?.includes(id)))return 'Espere todos chegarem fisicamente à sala.';}return ''};
Game.prototype.inviteMeeting=function(id,npc){let t=this.tasks.find(t=>t.id===id);if(!t||!t.participants.includes(npc)||this.location(D.npcs[npc])!==this.s.floor)return false;let m=this.s.meeting;if(!m||m.id!==id||m.day!==this.day)m=this.s.meeting={id,day:this.day,floor:t.floor,invited:[],readyAt:this.s.time+10};if(!m.invited.includes(npc)){m.invited.push(npc);m.readyAt=this.s.time+10;this.log(D.npcs[npc].name+' confirmou presença em '+t.name+'.');}return true};
const oldLocation=Game.prototype.location;Game.prototype.location=function(n){let m=this.s.meeting;if(m&&m.day===this.day&&m.invited.includes(n.id)&&this.s.time>=m.readyAt)return m.floor;return oldLocation.call(this,n)};
const oldStart=Game.prototype.startTask,oldFinish=Game.prototype.finishTask;
Game.prototype.startTask=function(id,approach='segura',practice=false){if(practice)return oldStart.call(this,id,approach,true);let reason=this.workReason(id,approach);if(reason){this.log(reason);return false}let t=this.tasks.find(t=>t.id===id),e=this.effort(approach),M=root.MINI||(typeof require!=='undefined'?require('./minigames.js'):null);let minutes=Math.round(t.minutes*e.factor),cost=Math.ceil(t.cost*e.cost);this.s.activeTask={id,career:true,rank:this.s.rank,step:t.step,approach,practice:false,floor:t.floor,q:Math.max(.35,.95-this.s.fatigue/300),overdue:this.hour+minutes>1080,points:t.points*e.reward,prestige:t.prestige*e.reward,name:t.name,mini:M.create(t.mini,Math.floor(this.s.time),e.difficulty)};this.s.energy-=cost;this.s.fatigue=Math.min(100,this.s.fatigue+Math.ceil(t.cost*e.cost));let key=this.day+':task:'+id;this.s.memory[key]=(this.s.memory[key]||0)+1;this.advance(minutes);this.log(t.name+': energia −'+cost+', '+minutes+' min.');return true};
Game.prototype.finishTask=function(){let a=this.s.activeTask;if(!a?.career)return oldFinish.call(this);if(a.mini.status==='playing')return false;let won=a.mini.status==='won';if(won){this.workflow.stage=Math.max(this.workflow.stage,a.step+1);this.s.challenge=true;if(a.id==='strategy'||a.rank===7&&a.step===3)this.s.strategic=true;}let result=oldFinish.call(this);if(won&&a.step===3)this.s.meeting=null;return result};
const oldRequirements=Game.prototype.requirements;
Game.prototype.requirements=function(){let rows=oldRequirements.call(this);if(this.s.rank>=7)return rows;let threshold=D.requirements[this.s.rank],floor=sponsors[this.s.rank];let valid=this.s.supports.filter(id=>(this.npcView?this.npcView(D.npcs[id]).floor:D.npcs[id].floor)>=floor&&this.s.relations[id]>=threshold.r);rows[2]={label:threshold.s+' recomendações do andar '+floor+' ou superior · confiança ≥ '+threshold.r,ok:valid.length>=threshold.s};let challenge=rows.find(r=>r.label.startsWith('Desafio:'));if(challenge)challenge.label='Desafio: concluir uma atividade do cargo';return rows};
const oldTalk=Game.prototype.talk;Game.prototype.talk=function(id,action){if(action==='support'&&(this.npcView?this.npcView(D.npcs[id]).floor:D.npcs[id].floor)<sponsors[this.s.rank]){this.log('Para a próxima promoção, procure recomendações do andar '+sponsors[this.s.rank]+' ou superior.');return false}return oldTalk.call(this,id,action)};
Game.prototype.personalLine=function(id){let n=D.npcs[id];return n.personalLines[this.s.relations[id]>=24?2:(this.day+id)%2]};
Game.careerTracks=tracks;Game.sponsorFloors=sponsors;
}
if(typeof module!=='undefined')module.exports=install;else install(root.Game,root.DATA);
})(typeof window!=='undefined'?window:globalThis);
