(function(root){
const roles=['Pleno','Sênior','Tech Lead','Gerente de Engenharia','Diretor de Engenharia','VP de Engenharia','CTO','CEO'];
const floors=['Operações & recepção','Desenvolvimento & operações','Plataforma','Liderança & gestão','Diretoria','Executivos','Presidência & conselho'];
const central=[['Lia Costa','Operações','colaborativa','café','Conhece quem resolve problemas de verdade.'],['Rui Melo','Analista de operações','oportunista','música','Troca informações por visibilidade.'],['Marta Ribeiro','Compras','colaborativa','plantas','Sabe negociar até o último centavo, sem perder a educação.'],['Renato Cardoso','Financeiro','hostil','xadrez','Não deixa um número errado passar despercebido.'],['Wagner Souza','Segurança predial','colaborativa','corrida','Sabe tudo o que acontece no prédio depois do expediente.'],['Helena Prado','Mentora sênior','colaborativa','livros','Está cansada de formar pessoas sem reconhecimento.'],['Caio Torres','Desenvolvedor sênior','hostil','jogos','Já apresentou trabalho alheio como próprio.'],['Paula Tavares','Recursos Humanos','colaborativa','aniversários','Sabe o aniversário de todo mundo antes de qualquer um lembrar do seu.'],['Diego Andrade','Marketing & Comunicação','oportunista','fotografia','Transforma qualquer entrega pequena em material de campanha.'],['Ivo Quental','Departamento pessoal','hostil','carimbos','Não libera nada com um formulário fora do prazo.'],['Iara Lima','Engenheira de plataforma','colaborativa','jardinagem','Quer reduzir alertas e noites sem dormir.'],['Breno Dias','Tech lead','oportunista','corrida','Disputa vagas com entregas rápidas.'],['Marcos Reis','Gerente pressionado','oportunista','café','Precisa entregar sem perder a equipe.'],['Nina Alves','Gerente de produto','colaborativa','cinema','Traduz conflitos em prioridades.'],['Clara Luz','Diretora de engenharia','colaborativa','livros','Exigente com evidências, generosa com crédito.'],['Otávio Sá','Diretor de plataforma','hostil','corrida','Quer a próxima cadeira executiva.'],['Davi Rocha','Executivo','oportunista','música','Evita compromissos até ver números.'],['Eva Ramos','VP de pessoas','colaborativa','jardinagem','Observa como líderes tratam quem não tem poder.'],['Sofia Vale','Conselheira','colaborativa','sustentabilidade','Crescimento precisa caber no futuro.'],['Artur Neves','CEO em sucessão','oportunista','cinema','Procura alguém capaz de unir execução e confiança.']];
const counts=[14,16,12,10,8,6,4], names=['Ana','Pedro','Beatriz','Lucas','Marta','Tiago','Joana','Daniel','Laura','Miguel','Alice','André','Cecília','Tomás','Inês','Raul'], surnames=['Silva','Campos','Freitas','Moura','Ribeiro','Pires','Azevedo'];
// Andar 1 começa menor de propósito: 5 pessoas com identidade própria, em vez de 14 com 12 genéricas.
const centralCounts=[5,5,2,2,2,2,2];
let cptr=0,npcs=[];counts.forEach((count,f)=>{for(let i=0;i<count;i++){let isCentral=i<centralCounts[f];let c=isCentral?central[cptr++]:[names[(i+f*3)%names.length]+' '+surnames[(i+f)%7],['Assistente de operações','Engenheiro de software','Especialista de infraestrutura','Coordenador','Diretor de produto','Executivo de negócios','Conselheiro'][f],['colaborativa','oportunista','hostil'][(i+f)%3],['café','livros','música','jardinagem','corrida','cinema'][(i+f)%6],'Busca equilíbrio entre qualidade, reconhecimento e sua equipe.']; npcs.push({id:npcs.length,name:c[0],job:c[1],personality:c[2],interest:c[3],context:c[4],floor:f+1,central:isCentral,influence:(f+1)*2,extra:i%5===0,start:8*60+(i%3)*15,end:i%5===0?20*60:18*60,slot:i,events:[]});}});
// Identidades estáveis: nunca renumerar os IDs usados pelos saves.
npcs[29].name='Beatriz Falcão';npcs[0].job='Recepcionista e operações';
const rolePools=[['Atendimento','Facilities','Suporte interno','Comunicação interna','Compras','Financeiro','Segurança predial'],['Engenharia frontend','Engenharia backend','Qualidade de software','Design de produto','Análise de produto'],['Confiabilidade de serviços','Administração de dados','Segurança de infraestrutura','Engenharia cloud'],['Gestão de produto','Coordenação de engenharia','Gestão de projetos'],['Direção de produto','Direção de operações','Direção de experiência'],['Estratégia de negócios','Liderança de pessoas'],['Conselho de tecnologia','Conselho de impacto']];npcs.filter(n=>!n.central).forEach(n=>n.job=rolePools[n.floor-1][n.slot%rolePools[n.floor-1].length]);
// Andar 2 divide-se em desenvolvimento, RH, marketing e departamento pessoal; o cargo de cada figurante segue a repartição onde fica sua mesa.
const floor2Jobs={5:'Engenharia frontend',6:'Engenharia backend',7:'Qualidade de software',8:'Recursos Humanos',9:'Recrutamento & seleção',10:'Marketing de conteúdo',11:'Redação publicitária',12:'Departamento pessoal',13:'Administração de benefícios'};
npcs.filter(n=>n.floor===2&&!n.central).forEach(n=>{if(floor2Jobs[n.slot])n.job=floor2Jobs[n.slot];});
const skins=['#f1c9a5','#b97850','#815034','#d89d75','#593b30','#edb995'];
const hairs=['#302c36','#713e2b','#d8a34f','#54382f','#b9b4b0','#202a32','#ad5e36'];
const clothes=['#477f88','#9b5c74','#6e77a5','#53836c','#c0814b','#705987','#47719a'];
const feminine=new Set(['Lia','Helena','Iara','Nina','Clara','Eva','Sofia','Ana','Beatriz','Marta','Joana','Laura','Alice','Cecília','Inês','Paula']);
npcs.forEach(n=>{n.appearance={skin:skins[n.id%skins.length],hair:hairs[(n.id*3)%hairs.length],shirt:clothes[(n.id*2)%clothes.length],style:n.id%5,glasses:n.id%4===0,gender:feminine.has(n.name.split(' ')[0])?'feminino':'masculino',accessory:n.id%3};});
for(const [id,style] of [[0,1],[14,3],[30,2],[42,1],[52,3],[60,0],[61,1],[66,4]])npcs[id].appearance.style=style;
// Appearance is a stable character design, shared by portraits and world sprites.
npcs.forEach(n=>{let a=n.appearance;a.style=a.gender==='feminino'?[1,3,2,4][n.id%4]:[0,2,4][n.id%3];a.beard=a.gender==='masculino'&&n.id%4===1;a.brows=a.gender==='masculino'?1.5:1;a.jaw=a.gender==='masculino'?9:8;a.accessory=a.gender==='feminino'?n.id%3:0;});
for(const [id,style] of [[0,1],[14,3],[30,2],[42,0],[52,4],[60,0],[61,3],[66,1],[67,4]])npcs[id].appearance.style=style;
const centralStories=[
 ['Bom te ver por aqui. Antes de procurar a sala mais importante, conheça quem faz este lugar funcionar.','Já ouvi seu nome nas equipes. Continue dividindo o crédito; as pessoas percebem.','Posso abrir algumas portas. Só não se esqueça de voltar para um café com a recepção.'],
 ['Sempre acontece alguma coisa por aqui. Você quer informação ou quer aparecer na reunião?','Tenho uma informação que pode ajudar. Mas faça sua parte quando a entrega sair.','Você cumpriu o combinado. Vou colocar seu nome na conversa certa.'],
 ['Precisa de material? Fale comigo antes de abrir um chamado. Economizo tempo e papel.','Consegui esticar o orçamento este mês. Não pergunte como; só aproveite.','Você pede as coisas certas, na hora certa. Isso facilita muito o meu lado.'],
 ['Toda nota que passa por essa mesa é conferida duas vezes. Qual é a sua?','Achei uma diferença de dois reais. Ninguém mais notaria, mas eu notei.','Suas contas sempre fecham direito. Isso conta mais do que parece por aqui.'],
 ['Rondo este prédio todo santo dia. Sei quem chega cedo e quem nunca sai a tempo.','Vi você aqui até tarde outra vez. Vá para casa; o prédio ainda vai estar de pé amanhã.','Você trata quem trabalha à noite com o mesmo respeito de quem trabalha de dia. Reparei nisso.'],
 ['Eu gosto de orientar. Só cansa ver gente subir e esquecer quem ajudou no começo. Como você costuma trabalhar?','Você voltou para contar o resultado. Isso importa mais para mim do que um agradecimento apressado.','Já vi você ajudar sem tomar o lugar do colega. Quero defender sua candidatura.'],
 ['Estão olhando os resultados deste trimestre. Espero que você tenha algo convincente para mostrar.','Você está documentando tudo, pelo visto. Então vamos ser bem claros sobre quem entregou o quê.','Seu histórico está difícil de contestar. Posso reconhecer isso, mesmo disputando a mesma vaga.'],
 ['Chegou bem na hora do lanche coletivo. Já sabe seu tipo sanguíneo? Eu gosto de estar preparada.','Separei um horário para você na integração de times. Aparecer nessas conversas conta mais do que parece.','Já falei seu nome numa reunião de reconhecimento. As pessoas confirmaram: você trata a equipe bem.'],
 ['Toda entrega vira uma história, se alguém souber contar. Qual é a sua até agora?','Usei um trecho do seu último resultado num comunicado interno. Ninguém reclamou, o que já é muito por aqui.','Vou colocar seu nome como referência na próxima campanha de recrutamento. Isso abre conversas.'],
 ['Antes de mais nada: seu cadastro está completo? Prefiro resolver isso logo, sem drama nenhum.','Seu formulário chegou certinho dessa vez. Confesso que fiquei surpreso.','Não costumo elogiar fácil por aqui, mas você trata prazo como se fosse número de verdade. Tem meu apoio.'],
 ['Passei a noite com alertas. Se você puder ajudar a remover uma causa de verdade, já melhora meu dia.','A equipe conseguiu dormir melhor depois daquela conversa. Vamos olhar os próximos riscos juntos?','Você entende que estabilidade também é uma entrega. Vou falar disso na avaliação.'],
 ['A próxima vaga deve abrir logo. Eu já estou escolhendo qual resultado vou apresentar.','Você entregou. Bom. Agora precisamos saber quem consegue repetir o resultado sem desgastar a equipe.','Somos concorrentes, mas eu reconheço um trabalho bem feito. Vamos competir com as regras claras.'],
 ['Tenho prazo apertado e uma equipe cansada. Preciso de uma proposta que caiba nos dois.','Você não prometeu o impossível. Isso me ajudou a negociar espaço para a equipe.','Quero ter mais líderes assim. Posso apoiar seu próximo passo com exemplos concretos.'],
 ['Engenharia quer qualidade, produto quer prazo. Antes de escolher um lado, me ajude a entender o problema.','A conversa ficou mais fácil quando você trouxe as pessoas para decidir juntas.','Você consegue transformar conflito em decisão. Eu vou lembrar disso na avaliação.'],
 ['Eu apoio boas ideias, mas preciso de evidências. Qual problema você resolveu, e quem participou?','Você trouxe números e reconheceu a equipe. Agora quero entender o que faria diferente.','Você aceita perguntas difíceis sem esconder os problemas. Tem meu apoio para liderar.'],
 ['Não há espaço para todo mundo na próxima rodada. Eu pretendo chegar preparado.','Você está ganhando visibilidade. Espero que as entregas acompanhem essa confiança toda.','Não vou fingir que somos amigos, mas seu trabalho merece uma avaliação justa.'],
 ['Talvez possamos conversar na semana que vem. Você consegue resumir o resultado em uma frase?','Agora eu entendi o impacto. Ainda preciso alinhar algumas coisas antes de assumir um compromisso.','Os resultados estão consistentes. Pode registrar meu apoio; vou sustentar essa posição.'],
 ['Quero saber como sua equipe termina o dia. Entregar tudo com todo mundo esgotado não resolve.','As pessoas me contaram que você escuta antes de distribuir trabalho. Continue assim.','Seu crescimento está criando espaço para outras pessoas. É por isso que vou apoiar você.'],
 ['Se crescermos hoje, quem paga a conta amanhã? Pessoas e recursos também precisam entrar no plano.','Gostei de ver sustentabilidade ligada a decisões concretas. Quais compromissos você consegue manter?','Você juntou resultado, responsabilidade e confiança. Vou levar seu nome ao conselho.'],
 ['Estou preparando minha sucessão. A cadeira precisa de alguém que una a empresa, não só suba os andares.','Seu nome chegou por pessoas de áreas diferentes. Agora quero ver como você decide sob pressão.','Você construiu algo que continua sem depender só de você. Está pronto para assumir a responsabilidade.']
];
npcs.filter(n=>n.central).forEach((n,i)=>n.events=centralStories[i]);
const taskScenes={
 bug:{intro:'O acesso falha para uma parte dos clientes. A equipe espera sua decisão.',choices:['Investigar a causa antes de corrigir','Chamar um colega para reproduzir o erro','Aplicar um remendo e monitorar'],reply:'Os testes de acesso terminaram. A equipe acompanha o resultado com você.'},
 review:{intro:'Uma colega pediu revisão antes de publicar. O prazo está apertado.',choices:['Conferir sozinho cada alteração','Revisar junto e explicar os riscos','Aprovar apenas o caminho principal'],reply:'A revisão voltou para a colega, com suas observações e o crédito compartilhado.'},
 feature:{intro:'Produto quer liberar um novo fluxo hoje. Ainda há dúvidas sobre os casos extremos.',choices:['Entregar um escopo menor, bem testado','Alinhar o fluxo com produto e design','Liberar tudo e corrigir depois'],reply:'O fluxo chegou à equipe. Sua escolha definiu o equilíbrio entre prazo e qualidade.'},
 incident:{intro:'Os alertas dispararam. Há clientes esperando e muita gente falando ao mesmo tempo.',choices:['Estabilizar o serviço e investigar','Organizar uma sala de resposta','Reiniciar sem investigar a causa'],reply:'O serviço respondeu. Agora a equipe registra o que aprendeu com o incidente.'},
 mentor:{intro:'Um colega travou no mesmo problema pela terceira vez. Ele pede ajuda, constrangido.',choices:['Preparar um guia para ele seguir','Resolver junto, deixando ele conduzir','Resolver por ele para ganhar tempo'],reply:'A conversa terminou. A autonomia que você ajudou a construir fica com o colega.'},
 strategy:{intro:'O conselho quer crescer sem aumentar o desgaste da equipe nem o consumo de infraestrutura.',choices:['Consolidar números antes da proposta','Construir um plano com equipes e conselho','Prometer expansão antes da análise'],reply:'A proposta circulou com responsáveis, custos e compromissos. O conselho leu sua decisão.'}
};
const tasks=[{id:'bug',name:'Bug no acesso',minutes:65,cost:12,points:2,prestige:2,desc:'Clientes não conseguem entrar.',best:'segura',min:0},{id:'review',name:'Revisão de qualidade',minutes:45,cost:9,points:1.5,prestige:2,desc:'Uma segunda leitura evita retrabalho.',best:'colaborativa',min:0},{id:'feature',name:'Funcionalidade de equipe',minutes:100,cost:18,points:3,prestige:3,desc:'Entregue um fluxo útil e acessível.',best:'segura',min:0},{id:'incident',name:'Incidente de produção',minutes:80,cost:20,points:3,prestige:4,desc:'Restaure o serviço e documente a causa.',best:'segura',min:1},{id:'mentor',name:'Mentoria de colega',minutes:60,cost:10,points:2,prestige:3,desc:'Ensine a equipe a resolver sem depender de você.',best:'colaborativa',min:2},{id:'strategy',name:'Proposta estratégica',minutes:110,cost:18,points:4,prestige:5,desc:'Coordene eficiência, pessoas e sustentabilidade.',best:'colaborativa',min:3}];
const balance={workdayStart:480,workdayEnd:1080,taskDailyLimit:2,forcedRestHours:8,extremeFatigue:95,socialFatigue:60,moveSpeed:180,saveInterval:10,rivalDailyProgress:34};
const layouts=[
 {name:'Recepção & convivência',theme:'#cbd4bd',feature:'Atendimento, suporte e encontros',objects:[['reception',90,245,260,64,'Atendimento & recepção'],['board',50,118,110,100,'Mural da empresa'],['partition',44,352,266,10,'Divisória da espera'],['partition',300,352,10,150,'Divisória da espera'],['sofa',88,376,190,44,'Espera de visitantes'],['lowtable',126,438,96,42,'Mesa de revistas'],['armchair',246,434,50,48,'Poltrona da espera'],['plant',42,438,48,62,'Jardim da recepção'],['counter',636,120,168,34,'Copa da equipe'],['coffee',816,110,110,110,'Café & conversa'],['cafetable',644,196,72,72,'Mesa do café'],['cafetable',788,268,72,72,'Mesa do café'],['printer',434,396,52,58,'Impressora & arquivo'],['desk',520,393,96,86,'Operações'],['desk',700,393,96,86,'Suporte de plantão'],['cabinet',858,392,54,92,'Arquivo da recepção']],seats:[[218,228],[568,500],[748,500],[690,300],[834,360],[160,520],[264,520],[430,300],[480,340],[560,180],[620,520],[880,300],[380,520],[840,540]]},
 // Quatro repartições lado a lado (não só desenvolvimento): cada uma com mesas e mural próprios, separadas por divisórias baixas em background().
 // Mesas/mural/café menores que o padrão do prédio (ver propSizes2) — com 14 pessoas neste andar, corredores largos importam mais que móveis grandes.
 {name:'Desenvolvimento & operações',theme:'#c5d3cc',feature:'Squads, RH, marketing e pessoal no mesmo andar',objects:[
  ['desk',50,225,72,64,'Estação de desenvolvimento'],['desk',190,225,72,64,'Estação de desenvolvimento'],['desk',50,360,72,64,'Estação de desenvolvimento'],['desk',190,360,72,64,'Estação de desenvolvimento'],
  ['desk',390,225,72,64,'Recursos Humanos'],['desk',390,360,72,64,'Recursos Humanos'],
  ['desk',590,225,72,64,'Marketing & Comunicação'],['desk',590,360,72,64,'Marketing & Comunicação'],
  ['desk',800,225,72,64,'Departamento pessoal'],['desk',800,360,72,64,'Departamento pessoal'],
  // Os 4 murais ficavam colados à parede de cima, bem no único corredor entre o elevador e o resto do
  // andar — qualquer pessoa parada ali (jogador incluído) virava um tampão no gargalo. Movidos para a
  // faixa de baixo, junto da própria repartição, deixando o corredor de cima livre de ponta a ponta.
  ['board',45,460,64,56,'Quadro da sprint'],['board',345,460,64,56,'Quadro de vagas'],['board',550,460,64,56,'Mural de campanhas'],['board',755,460,64,56,'Quadro de ponto'],
  // Café + mesinha saem do meio do corredor de baixo (entre os murais) e vão para o canto livre em
  // cima à direita — fora da rota principal de quem chega pelo elevador.
  ['coffee',840,125,48,50,'Café'],['cafetable',740,130,64,64,'Mesa do café'],
  ['plant',305,175,32,35,'Planta'],['plant',510,175,32,35,'Planta'],['plant',680,460,32,35,'Planta']
 ],seats:[[86,307],[226,307],[426,307],[626,307],[836,307],[86,442],[226,442],[77,530],[426,442],[377,530],[626,442],[582,530],[836,442],[787,530]]},
 {name:'Plataforma & observabilidade',theme:'#b4c9d4',feature:'Serviços que não dormem',objects:[['rack',85,190,60,120,'Servidores'],['rack',170,190,60,120,'Servidores'],['rack',255,190,60,120,'Servidores'],['console',570,205,300,70,'Central de incidentes'],['desk',610,370,130,55,'Confiabilidade'],['board',90,415,230,32,'Mapa de serviços'],['coffee',800,445,80,45,'Café']],seats:[[670,185],[665,345],[100,350],[210,350],[300,350],[390,210],[810,330],[870,385],[340,480],[520,480],[660,480],[780,525]]},
 {name:'Liderança & planejamento',theme:'#d3c8b8',feature:'Decidir juntos',objects:[['meeting',100,220,270,105,'Reunião de equipe'],['board',610,170,240,38,'Planejamento'],['desk',650,280,165,62,'Coordenação'],['sofa',120,420,200,50,'Mentoria'],['coffee',760,440,110,50,'Café']],seats:[[690,260],[190,198],[110,360],[280,360],[370,350],[580,340],[855,290],[635,440],[320,505],[740,525]]},
 {name:'Diretoria & decisões',theme:'#d6cbbb',feature:'Prioridades com consequências',objects:[['executive',95,240,250,76,'Direção de engenharia'],['executive',625,240,240,76,'Direção de plataforma'],['meeting',350,390,260,90,'Comitê técnico'],['board',75,140,220,35,'Portfólio'],['coffee',795,440,90,45,'Café']],seats:[[225,215],[750,215],[130,365],[310,350],[650,350],[810,360],[295,465],[675,460]]},
 {name:'Executivos & negociação',theme:'#c1cbd6',feature:'O futuro em discussão',objects:[['meeting',115,205,270,110,'Mesa de negociação'],['sofa',670,230,200,58,'Conversa reservada'],['executive',130,430,210,64,'Vice-presidência'],['board',630,145,230,38,'Cenários de crescimento'],['coffee',775,450,110,50,'Café']],seats:[[220,185],[745,210],[370,350],[610,355],[225,400],[680,480]]},
 {name:'Conselho & presidência',theme:'#d4d7bd',feature:'Crescer com responsabilidade',objects:[['boardtable',240,250,465,100,'Conselho'],['executive',735,420,155,60,'Presidência'],['garden',80,180,70,230,'Jardim de inverno'],['board',685,145,220,40,'Plano sustentável']],seats:[[315,225],[620,225],[350,385],[620,385]]}
].map((l,i)=>({...l,floor:i+1,objects:l.objects.map((o,k)=>({id:k,type:o[0],x:o[1],y:o[2],w:o[3],h:o[4],label:o[5]}))}));
// World units: a character is 52px tall. Shared props use one physical size on every floor.
const propSizes={desk:[96,86],board:[90,84],coffee:[64,68],plant:[32,35]};
// Andar 2 tem 14 pessoas para só 10 secretárias reais: móveis um pouco menores liberam corredor sem esvaziar o andar.
const propSizes2={desk:[72,64],board:[64,56],coffee:[48,50],plant:[32,35]};
for(const l of layouts)for(const o of l.objects){const size=(l.floor===2?propSizes2:propSizes)[o.type];if(!size)continue;
 const cx=o.x+o.w/2,bottom=o.y+o.h;[o.w,o.h]=size;o.x=cx-o.w/2;o.y=bottom-o.h;
}
const influenceAccess=[0,0,12,24,40,60,85];
// Visitas entre andares são poucas e nomeadas de propósito — cada uma é uma rotina fixa de uma pessoa específica, não um fluxo genérico de "todo mundo do andar X visita o andar Y".
const visits={1:[{from:600,to:660,floor:3,reason:'Levando demandas de operações'}],14:[{from:840,to:900,floor:4,reason:'Mentoria a convite da liderança'}],15:[{from:900,to:945,floor:3,reason:'Articulando a próxima vaga'}],31:[{from:900,to:945,floor:3,reason:'Reunião informal com Caio'}],53:[{from:900,to:960,floor:6,reason:'Negociando apoio executivo'}],61:[{from:720,to:810,floor:1,reason:'Visitando a recepção no almoço'}],67:[{from:720,to:810,floor:1,reason:'Conferindo o andar térreo pessoalmente'}]};
const workload={bug:12,review:5,feature:20,incident:24,mentor:7,strategy:18};
const config={layouts,influenceAccess,visits,workload,taskScenes,balance,roles,floors,counts,npcs,tasks,normal:{reward:1,relation:1,minDays:2},demo:{reward:3,relation:2,minDays:0},requirements:[{d:5,p:6,s:1,r:12},{d:12,p:14,s:2,r:14},{d:22,p:25,s:2,r:16},{d:34,p:38,s:3,r:18},{d:48,p:54,s:3,r:20},{d:64,p:72,s:4,r:22},{d:82,p:92,s:4,r:24}]}; root.DATA=config;if(typeof module!=='undefined')module.exports=config;
})(typeof window!=='undefined'?window:globalThis);
