(function(root){const D=root.DATA||(typeof require!=='undefined'?require('./data.js'):null);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class Game{
constructor(mode='normal',saved){this.s=saved||{version:1,mode,time:480,rank:0,floor:1,x:480,y:470,energy:100,fatigue:0,prestige:0,deliveries:0,relations:D.npcs.map(()=>0),memory:{},supports:[],invitations:[],prepared:false,strategic:false,challenge:false,promotedDay:1,vacancyUntil:3,reopen:0,losses:0,logs:[],appointments:[],evidence:false,victory:false};if(!this.s.rivals)this.s.rivals=[{id:15,name:'Caio Torres',progress:0},{id:31,name:'Breno Dias',progress:0},{id:55,name:'Otávio Sá',progress:0}];for(const rival of this.s.rivals){const npc=D.npcs.find(n=>n.name===rival.name);if(npc)rival.id=npc.id;}this.s.story=this.s.story||{events:{},presented:{},deferred:{}};this.s.facing=this.s.facing||'down';if(!saved)this.log('Bem-vindo à Nimbus. Converse com Lia, faça entregas e construa apoios.');}
storyOffer(npc){return Game.episodes.find(e=>(npc===undefined||e.npc===npc)&&this.location(D.npcs[e.npc])===this.s.floor&&e.ready(this)&&!['closed','declined'].includes(this.s.story.events[e.id])&&(this.s.story.deferred[e.id]||0)<=this.day)}
storyChoose(id,choice){let e=this.storyOffer();if(!e||e.id!==id)return false;let state=this.s.story.events[id];if(choice==='later'){this.s.story.deferred[id]=this.day+1;this.log(D.npcs[e.npc].name+': conversa adiada para amanhã.');return true}if(state==='done'&&choice==='accept'){this.s.story.events[id]='closed';this.relation(e.npc,4);this.log(e.title+': resolvido. '+D.npcs[e.npc].name+' lembra da sua ajuda.');return true}if(state)return false;if(choice==='accept'){this.s.story.events[id]='accepted';this.log(e.title+': '+e.goal);return true}if(choice==='decline'){this.s.story.events[id]='declined';this.log(e.title+': você preferiu não assumir.');return true}return false}
storyText(id){let e=Game.episodes.find(e=>e.npc===id&&this.s.story.events[e.id]);if(!e)return '';let state=this.s.story.events[e.id];return state==='closed'?e.after:state==='declined'?e.refused:state==='accepted'?(this.s.lastTaskOutcome?.won===false?'Vi que a tentativa não deu certo. Respira. Podemos tentar de novo. ': '')+e.wait:e.end}
get cfg(){return D[this.s.mode]} get day(){return Math.floor(this.s.time/1440)+1}get hour(){return this.s.time%1440}get influence(){return Math.round(D.npcs.reduce((a,n)=>a+Math.max(0,this.s.relations[n.id])*n.influence/30,0))}log(t){this.s.logs.unshift('D'+this.day+' '+this.clock()+' · '+t);this.s.logs=this.s.logs.slice(0,100)}clock(){return String(Math.floor(this.hour/60)).padStart(2,'0')+':'+String(Math.floor(this.hour%60)).padStart(2,'0')}
advance(m,resting=false){if(!resting)this.s.fatigue=clamp(this.s.fatigue+m*.004,0,100);let before=this.hour,day=this.day;this.s.time+=m; if(this.s.reopen&&this.day>=this.s.reopen){this.s.reopen=0;this.s.vacancyUntil=this.day+3;for(let rival of this.s.rivals)rival.progress=0;this.log('Nova rodada de seleção aberta por 3 dias.');} if(before<1080&&(this.hour>=1080||this.day>day))this.log('18h: o expediente terminou. Conversas rendem menos; extras cansam.');if(this.day>day){for(let rival of this.s.rivals)rival.progress=clamp(rival.progress+D.balance.rivalDailyProgress*(this.day-day),0,100);this.s.energy=clamp(this.s.energy-5,0,100);if(this.day>this.s.vacancyUntil&&!this.s.reopen&&!this.s.victory){this.lose();} }if(this.hour>=960&&this.day%3===0&&this.s.deliveries>8&&!this.s.memory[this.day+':plot']){this.s.memory[this.day+':plot']=true;let defender=this.s.supports.find(id=>this.s.relations[id]>=24);if(defender!==undefined)this.log(D.npcs[defender].name+' defendeu seu crédito na conversa dos rivais.');else{this.s.prestige=Math.max(0,this.s.prestige-2);this.log('Caio e Breno omitiram seu crédito. Prestígio −2. Quem ouviu a conversa na plataforma pode responder com evidência.');}}for(const a of this.s.appointments){if(!a.done&&this.s.time>a.at+45){a.done=true;this.s.relations[a.id]-=3;this.log('Compromisso perdido com '+D.npcs[a.id].name+': relação −3.');}}}
lose(){this.s.losses++;this.s.reopen=this.day+1;this.log(['Caio','Breno','Otávio'][this.s.rank%3]+' ganhou a rodada. Nova vaga amanhã; seus requisitos e apoios permanecem.');}
access(f){return Number.isInteger(f)&&f>=1&&f<=7&&(f<=Math.min(7,this.s.rank+2)||this.s.invitations.includes(f)||this.influence>=D.influenceAccess[f-1])}go(f){if(!this.access(f))return false;this.s.floor=f;this.s.x=480;this.s.y=140;return true}
location(n){let coffee=this.s.appointments.find(a=>a.id===n.id&&!a.done&&this.s.time>=a.at-10&&this.s.time<=a.at+45);if(coffee)return coffee.floor||n.floor;if(this.hour<n.start||this.hour>=n.end)return 0;if(n.floor>=6&&this.hour>=720&&this.hour<810)return 1;let visit=(D.visits[n.id]||[]).find(v=>this.hour>=v.from&&this.hour<v.to);return visit?visit.floor:n.floor}
relation(id,delta){this.s.relations[id]=clamp(this.s.relations[id]+delta,-20,100)}
talk(id,action){const n=D.npcs[id];if(!n||!this.location(n)){this.log('A pessoa encerrou o expediente. Retome a conversa amanhã.');return false;}const key=this.day+':'+id+':'+action;let count=this.s.memory[key]||0;if(count){this.log('Já conversaram sobre isso hoje. Sem ganho repetido.');return false}this.s.memory[key]=1;let r=this.s.relations[id],delta=0,minutes=15;const threshold=8+n.floor*2;
if(action==='listen'){delta=6;this.log(n.name+': “'+n.interest+' me ajuda a desligar. Obrigado por ouvir.”');}
if(action==='help'){delta=8;minutes=30;this.s.energy-=5;this.s.deliveries+=.5*this.cfg.reward;this.log('Você ajudou '+n.name+' e dividiu o crédito. Entregas +'+(.5*this.cfg.reward)+'.');}
if(action==='share'){delta=this.s.deliveries>=n.floor*2?7:-3;this.log(delta>0?'Evidências e crédito compartilhado fortaleceram a confiança.':'Faltam entregas para sustentar o pedido; relação −3.');}
if(action==='advice'){delta=4;this.s.prepared=true;this.log('Orientação recebida: próxima tarefa ganha preparo (+15% qualidade).');}
if(action==='support'){if(r>=threshold&&this.s.deliveries>=n.floor*2){if(!this.s.supports.includes(id))this.s.supports.push(id);delta=2;this.s.invitations.push(Math.min(7,n.floor+1));this.log(n.name+' confirmou apoio e apresentou você ao próximo andar.');}else{delta=-4;this.log('Pedido prematuro: precisa relação '+threshold+' e '+n.floor*2+' entregas. Relação −4.');}}
if(action==='coffee'){this.s.appointments.push({id,at:this.s.time+60,done:false,floor:this.s.floor});this.log('Café combinado com '+n.name+' em uma hora. Volte pela Agenda (janela de 45 min).');}
if(action==='defend'){if(this.s.evidence){this.s.prestige+=3;delta=3;this.s.evidence=false;this.log('Registro de autoria corrigiu o rumor. Prestígio +3.');}else{delta=-2;this.log('Sem evidência, a acusação prejudica a conversa.');}}
if(this.hour>=1080){delta=Math.min(delta,2);this.log('Fora do expediente: disposição social reduzida.');}if(this.s.fatigue>D.balance.socialFatigue)delta=Math.floor(delta*.5);if(delta>0&&n.personality==='hostil'&&action!=='share'&&action!=='defend'){delta=Math.max(1,delta-2);this.log(n.name+' exige mais evidências: ganho de confiança reduzido em 2.');}if(delta>0&&n.personality==='oportunista'&&action==='share')delta+=2;this.relation(id,delta*this.cfg.relation);this.log('Relação com '+n.name+': '+(delta>=0?'+':'')+(delta*this.cfg.relation)+'.');this.advance(minutes);this.checkFatigue();return true;}
attend(i){let a=this.s.appointments[i];if(!a||a.done||this.s.time<a.at||this.s.time>a.at+45)return false;a.done=true;this.relation(a.id,10*this.cfg.relation);this.s.energy=clamp(this.s.energy+8,0,100);this.advance(20);this.log('Café cumprido: confiança +'+10*this.cfg.relation+', energia +8.');return true}
get workflow(){if(!this.s.workflow||this.s.workflow.day!==this.day)this.s.workflow={day:this.day,stage:0};return this.s.workflow}
workReason(id){if(this.s.activeTask)return 'Conclua a atividade em andamento.';const t=D.tasks.find(t=>t.id===id);if(!t)return 'Demanda não encontrada.';if(this.hour<480||this.hour>=1200)return 'Escritório fechado. Retorne às 8h.';if(this.s.rank<t.min)return 'Disponível a partir de '+D.roles[t.min]+'.';if(this.s.energy<t.cost)return 'Energia insuficiente. Faça uma pausa.';if((this.s.memory[this.day+':task:'+id]||0)>=2)return 'Tentativas de hoje encerradas. Escolha outra atividade.';if(id==='review'&&this.workflow.stage<1)return 'Primeiro: diagnosticar o bug da sprint.';if(id==='feature'&&this.workflow.stage<2)return 'Primeiro: concluir a revisão.';if(id==='strategy'&&this.workflow.stage<3)return 'Primeiro: implementar a entrega da sprint.';const duration=t.minutes*(this.s.approach==='rápida'?.7:this.s.approach==='colaborativa'?1.1:1);if(this.hour+duration>1200)return 'Não há tempo útil suficiente para concluir esta atividade hoje. Retorne amanhã.';return '';}
work(id,approach){return this.startTask(id,approach)}
startTask(id,approach='segura',practice=false){if(this.s.activeTask)return false;let reason=practice?'':this.workReason(id);if(reason){this.log(reason);return false}let t=practice?{id,name:'Desafio do andar',minutes:20,cost:6,points:0,prestige:1}:D.tasks.find(t=>t.id===id);if(practice&&(this.hour<480||this.hour>=1200||this.s.energy<6||this.s.memory[this.day+':room:'+this.s.floor]))return false;const M=root.MINI||(typeof require!=='undefined'?require('./minigames.js'):null);let q=clamp(.65+(approach===t.best?.25:approach==='rápida'?-.12:.08)+(this.s.prepared?.15:0)-this.s.fatigue/220,.25,1.05),duration=Math.round(t.minutes*(approach==='rápida'?.7:approach==='colaborativa'?1.1:1)),overdue=this.hour+duration>1080;this.s.activeTask={id,approach,practice,floor:this.s.floor,q,overdue,points:t.points,prestige:t.prestige,name:t.name,mini:M.create(id,Math.floor(this.s.time)+this.s.rank*29,Math.min(3,1+Math.floor(this.s.rank/3)))};this.s.energy-=t.cost;this.s.fatigue=clamp(this.s.fatigue+(practice?4:D.workload[id])+(overdue?8:0),0,100);this.s.prepared=false;let key=practice?this.day+':room:'+this.s.floor:this.day+':task:'+id;this.s.memory[key]=(this.s.memory[key]||0)+1;this.advance(duration);this.log(t.name+': esforço reservado, energia −'+t.cost+'. Resolva a atividade para entregar.');return true}
miniMove(value){if(!this.s.activeTask)return false;const M=root.MINI||(typeof require!=='undefined'?require('./minigames.js'):null);M.act(this.s.activeTask.mini,value);if(this.s.activeTask.mini.status!=='playing')this.finishTask();return true}
finishTask(){let a=this.s.activeTask;if(!a||a.mini.status==='playing')return false;let won=a.mini.status==='won',q=clamp(a.q-a.mini.mistakes*.06,.25,1.05);if(won){this.s.deliveries+=a.points*q*this.cfg.reward;this.s.prestige+=a.prestige*q*this.cfg.reward;if(a.practice){let n=D.npcs.find(n=>n.floor===a.floor&&n.central);this.relation(n.id,3);this.s.prepared=true;}else{if(a.id==='bug')this.workflow.stage=Math.max(1,this.workflow.stage);if(a.id==='review')this.workflow.stage=Math.max(2,this.workflow.stage);if(a.id==='feature')this.workflow.stage=Math.max(3,this.workflow.stage);if(a.id==='strategy')this.s.strategic=true;if(q>=.65)this.s.challenge=true;}}if(a.overdue&&!a.practice)this.s.prestige=Math.max(0,this.s.prestige-1);if(won&&!a.practice)for(const e of Game.episodes){if(this.s.story.events[e.id]==='accepted'&&e.task===a.id){this.s.story.events[e.id]='done';this.log(e.title+': entrega pronta. Procure '+D.npcs[e.npc].name+'.');}}this.s.lastTaskOutcome={won,id:a.id,name:a.name,quality:Math.round(q*100),deliveries:won?a.points*q*this.cfg.reward:0,practice:a.practice};this.log(won?a.name+': concluída, '+Math.round(q*100)+'% de qualidade.':a.name+': tentativa não concluída. Esforço consumido, sem recompensa.');this.s.activeTask=null;this.checkFatigue();return won}
abortTask(){if(!this.s.activeTask)return;this.s.activeTask.mini.status='lost';this.finishTask()}
takeBreak(){let key=this.day+':break';if((this.s.memory[key]||0)>=3||this.s.activeTask)return false;this.s.memory[key]=(this.s.memory[key]||0)+1;this.advance(20);this.s.energy=clamp(this.s.energy+16,0,100);this.s.fatigue=clamp(this.s.fatigue-12,0,100);this.log('Pausa no café: energia +16, fadiga −12.');return true}
observePlot(){if(this.s.floor!==3||this.hour<900||this.hour>=945)return false;this.s.evidence=true;this.advance(5);this.log('Você ouviu Caio e Breno articulando crédito. Evidência registrada para responder.');return true}
rest(hours){this.advance(hours*60,true);this.s.energy=clamp(this.s.energy+hours*12,0,100);this.s.fatigue=clamp(this.s.fatigue+(hours<7?(7-hours)*6:-hours*8),0,100);this.log('Descanso de '+hours.toFixed(1)+'h: energia '+Math.round(this.s.energy)+', fadiga '+Math.round(this.s.fatigue)+'.');this.s.floor=1;this.s.x=480;this.s.y=460}
endDay(hours=8){hours=clamp(Number(hours)||8,2,10);this.rest(hours);let before=this.s.time;if(this.hour<480)this.advance(480-this.hour,true);else if(this.hour>=1080)this.advance(1440-this.hour+480,true);if(this.s.time>before)this.log('Tempo pessoal até a abertura. Retorno às 08h; recuperação corresponde apenas às '+hours+'h de sono.');this.s.floor=1;this.s.x=480;this.s.y=490;return true;}
nextMorning(){let target=Math.floor(this.s.time/1440)*1440+480;if(target<=this.s.time)target+=1440;this.rest((target-this.s.time)/60)}checkFatigue(){if(this.s.fatigue>=D.balance.extremeFatigue||this.s.energy<=0){this.log('Exaustão: descanso protegido de 8h. Nenhuma vaga fica bloqueada permanentemente.');this.endDay(D.balance.forcedRestHours)}}
requirements(){if(this.s.rank>=7)return [];let r=D.requirements[this.s.rank],valid=this.s.supports.filter(id=>this.s.relations[id]>=r.r),strategicDone=this.s.strategic||(this.s.lastTaskOutcome?.id==='strategy'&&this.s.lastTaskOutcome.won);return [{label:r.d+' entregas',ok:this.s.deliveries>=r.d},{label:r.p+' prestígio',ok:this.s.prestige>=r.p},{label:r.s+' apoios com relação ≥ '+r.r,ok:valid.length>=r.s},{label:'Desafio: uma entrega de qualidade ≥65% neste cargo',ok:this.s.challenge},{label:'Experiência: '+this.cfg.minDays+' dias no cargo',ok:this.day-this.s.promotedDay>=this.cfg.minDays},{label:'Vaga disponível',ok:!this.s.reopen||this.day>=this.s.reopen},...(this.s.rank===6?[{label:'Proposta estratégica de qualidade',ok:strategicDone},{label:'Apoio de Sofia ou Artur (conselho)',ok:valid.some(id=>D.npcs[id].floor===7)}]:[])]}
promote(){if(this.requirements().some(r=>!r.ok)||this.s.rank===7)return false;this.s.rank++;for(let rival of this.s.rivals)rival.progress=0;this.s.promotedDay=this.day;this.s.challenge=false;this.s.reopen=0;this.s.vacancyUntil=this.day+3;this.log('Promoção conquistada: '+D.roles[this.s.rank]+'. Trabalho e rede reconhecidos.');if(this.s.rank===7){this.s.victory=true;this.log('Você assumiu a Nimbus. O próximo andar pertence a toda a equipe.');}return true}
}Game.episodes=[
{id:'reception',npc:0,title:'A fila não anda',task:'bug',ready:g=>g.hour>=485,
intro:'Ei, tem um minuto? O cadastro de visitantes travou de novo. Estão reclamando comigo como se eu tivesse quebrado aquilo… Você consegue investigar?',goal:'Concluir um diagnóstico e voltar à Lia.',wait:'Ainda estou anotando os visitantes no papel. Quando terminar o diagnóstico, me avisa?',end:'Funcionou! A fila finalmente andou. Desculpa o jeito de antes… eu estava me sentindo sozinha aqui.',after:'Guardei aquela folha de visitantes. Lembra da confusão? Agora sei a quem pedir ajuda.',refused:'Consegui contornar com papel por enquanto. Sei que você também tem suas prioridades.'},
{id:'review',npc:14,title:'Antes de apertar publicar',task:'review',ready:g=>g.s.deliveries>0,
intro:'Preciso de outro par de olhos. Encontrei uma falha, mas o Caio quer publicar assim mesmo. Não quero transformar isso numa briga. Você revisa comigo?',goal:'Concluir uma revisão e voltar à Helena.',wait:'Separei os pontos duvidosos. Quero discutir fatos, sem expor ninguém na reunião.',end:'Você também encontrou. Obrigada. Agora consigo pedir a correção com um registro, sem virar uma disputa pessoal.',after:'A revisão que fizemos mudou o clima da reunião. O Caio não gostou da espera, mas o problema ficou registrado.',refused:'Vou fazer a revisão sozinha. Prefiro atrasar um pouco a deixar isso chegar ao cliente.'},
{id:'credit',npc:15,title:'De quem é a entrega?',task:'feature',ready:g=>g.s.story.events.review==='closed',
intro:'A Helena disse que vocês seguraram a publicação. Eu estava pressionado pelo prazo… Vamos fechar a implementação juntos? Desta vez eu coloco os nomes de todo mundo.',goal:'Concluir uma implementação e voltar ao Caio.',wait:'Estou esperando a implementação. Deixei a autoria compartilhada no relatório; pode conferir.',end:'Entregamos. E sim, seu nome está lá. Não sou bom em admitir isso, mas a revisão evitou um problema maior.',after:'Ainda discordo de você sobre prazos. Mas naquela entrega você fez sua parte — não vou apagar isso.',refused:'Entendi. Depois daquela reunião, eu também teria um pé atrás. Vou fechar minha parte.'}
];
root.Game=Game;if(typeof module!=='undefined'){require('./careers.js')(Game,D);require('./living.js')(Game,D);module.exports=Game;}})(typeof window!=='undefined'?window:globalThis);
