(function(root){function install(Game,D){
if(Game.livingInstalled)return;Game.livingInstalled=true;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const routineNoise=(id,day,salt=0)=>{let x=(Math.imul(id+17,2654435761)^Math.imul(day+7,1597334677)^Math.imul(salt+1,2246822519))>>>0;x=Math.imul(x^(x>>>16),2246822507);x=Math.imul(x^(x>>>13),3266489909);return ((x^(x>>>16))>>>0)/4294967296;};
const noise=(id,day,salt=0)=>((Math.imul(id+17,2654435761)^Math.imul(day+7,1597334677)^salt)>>>0)/4294967296;
// Redistribute two secondary characters without changing any saved identity.
D.counts=[16,14,12,10,8,6,4];for(let i=0;i<2;i++){D.npcs[28+i].floor=1;D.npcs[28+i].slot=14+i;}D.layouts[0].seats.push([405,390],[560,390]);
Game.prototype.society=function(){if(!this.s.society)this.s.society={day:this.day,people:D.npcs.map(n=>({id:n.id,floor:n.floor,slot:n.slot,prestige:20+n.floor*10,performance:0,breakMinutes:0,anger:0})),gossip:{},choices:{},lastReview:this.day,playerStrikes:0};return this.s.society};
// A reception has two permanent staff and one rotating support shift, not sixteen desks.
// Rotação limitada ao elenco com identidade própria: um andar pequeno, não uma fila anônima.
Game.prototype.receptionRoster=function(){let people=this.society().people.filter(p=>p.floor===1).map(p=>p.id),fixed=people.filter(id=>id===0||id===1),rest=people.filter(id=>!fixed.includes(id)&&D.npcs[id].central);let support=rest.length?rest[(this.day-1)%rest.length]:null;let visitors=rest.filter(id=>id!==support),visitor=visitors.length?visitors[Math.floor(this.hour/60)%visitors.length]:null;return {fixed,support,visitor};};
Game.prototype.npcView=function(n){let p=this.society().people[n.id];let roster=p.floor===1?this.receptionRoster():null;let receptionSlot=roster?(n.id===0?0:n.id===1?1:n.id===roster.support?2:3):p.slot;return {...n,floor:p.floor,slot:receptionSlot,job:roster?(n.id===0?'Recepcionista':n.id===1?'Analista de operações':n.id===roster.support?'Suporte de plantão':'Visitante · '+n.job):p.floor===n.floor?n.job:'Equipe de '+D.floors[p.floor-1],mood:p.anger?'angry':'neutral'}};
Game.prototype.sectionChief=function(f){return this.society().people.filter(p=>p.floor===f).sort((a,b)=>b.prestige-a.prestige||a.id-b.id)[0]?.id};
Game.prototype.routine=function(n){let p=this.society().people[n.id],start=570+Math.floor(routineNoise(n.id,this.day,991)*150),second=855+Math.floor(routineNoise(n.id,this.day,557)*145),length=22+Math.floor(routineNoise(n.id,this.day,773)*7);
if(p.floor===1){let r=this.receptionRoster(),shared=675+Math.floor(routineNoise(1,this.day,772)*20);if(n.id===1||n.id===r.support)start=shared+(n.id===r.support?3:0);if(n.id===0)start=shared+35;}
return {first:start,second,length,onBreak:(this.hour>=start&&this.hour<start+length)||(this.hour>=second&&this.hour<second+length),chief:this.sectionChief(p.floor)===n.id};};
const previousLocation=Game.prototype.location;
Game.prototype.location=function(n){let m=this.s.meeting;if(m&&m.day===this.day&&m.invited.includes(n.id)&&this.s.time>=m.readyAt)return m.floor;let a=this.s.appointments.find(a=>a.id===n.id&&!a.done&&this.s.time>=a.at-10&&this.s.time<=a.at+45);if(a)return a.floor||n.floor;if(this.hour<n.start||this.hour>=n.end)return 0;let p=this.society().people[n.id];let v=(D.visits[n.id]||[]).find(v=>this.hour>=v.from&&this.hour<v.to);if(v)return v.floor;if(p.floor===1){let r=this.receptionRoster();if(r.fixed.includes(n.id)||n.id===r.support)return 1;if(n.id===r.visitor&&this.hour%60>=15&&this.hour%60<40)return 1;return 0;}return p.floor;};
Game.prototype.socialChoice=function(id,choice){if(!['empathize','disagree','mock','apologize'].includes(choice)||this.location(D.npcs[id])!==this.s.floor)return null;let sim=this.society(),key=this.day+':'+id+':'+choice;if(sim.choices[key])return {text:'Já conversamos sobre isso hoje. Vamos dar um tempo.',delta:0};sim.choices[key]=true;let person=sim.people[id],delta,text;if(choice==='empathize'){delta=3;text='Obrigado por ouvir. Não precisava concordar com tudo para ficar aqui comigo.';}if(choice==='disagree'){delta=D.npcs[id].personality==='hostil'?-2:1;text=delta<0?'Eu não gostei de ouvir isso. Preciso pensar antes de continuar.':'Discordamos, mas você explicou seu ponto sem me diminuir. Tudo bem.';}if(choice==='mock'){delta=-12;person.anger+=2;text='Isso era importante para mim. Não te contei para virar piada. Agora prefiro ficar sozinho.';}if(choice==='apologize'){delta=person.anger>0?4:0;person.anger=Math.max(0,person.anger-1);text=delta?'Aceito que você reconheça. A confiança vai levar mais tempo para voltar.':'Não há nada para resolver agora.';}this.relation(id,delta);this.advance(5);this.log(D.npcs[id].name+': relação '+(delta>=0?'+':'')+delta+'.');return {text,delta};};
Game.prototype.spreadGossip=function(source,target){let sim=this.society(),p=sim.people[source],key=this.day+':'+source;if(p.anger<1||sim.gossip[key]||source===target)return false;sim.gossip[key]=true;this.relation(target,-2);this.s.prestige=Math.max(0,this.s.prestige-2);this.recordPerformance(false,'Abalo de reputação por conflito',0);this.log(D.npcs[source].name+' contou a '+D.npcs[target].name+' que se sentiu desrespeitado. Prestígio −2; confiança com quem ouviu −2.');return true;};
Game.prototype.reviewSociety=function(){let sim=this.society();while(sim.day<this.day){sim.day++;for(let p of sim.people){let change=Math.floor(noise(p.id,sim.day,812)*9)-3-(p.breakMinutes>45?4:0);p.performance=change;p.prestige=clamp(p.prestige+change,0,150);p.breakMinutes=0;}
// Adjacent-floor swaps keep every seat occupied exactly once and preserve the pyramid.
for(let f=1;f<7;f++){let lower=sim.people.filter(p=>p.floor===f).sort((a,b)=>b.prestige-a.prestige),upper=sim.people.filter(p=>p.floor===f+1).sort((a,b)=>a.prestige-b.prestige);let up=lower[0],down=upper[0];if(up.prestige>down.prestige+8){[up.floor,down.floor]=[down.floor,up.floor];[up.slot,down.slot]=[down.slot,up.slot];this.log(D.npcs[up.id].name+' subiu ao andar '+up.floor+'; '+D.npcs[down.id].name+' foi realocado para o andar '+down.floor+'.');}}}};
const previousAdvance=Game.prototype.advance;Game.prototype.advance=function(m,rest=false){this.society();previousAdvance.call(this,m,rest);this.reviewSociety();};
Game.prototype.recordPerformance=function(success,reason='Entrega não concluída',penalty=4){let sim=this.society();if(success){sim.playerStrikes=Math.max(0,sim.playerStrikes-1);return;}this.s.prestige=Math.max(0,this.s.prestige-penalty);sim.playerStrikes++;this.log(reason+': prestígio −'+penalty+'. '+sim.playerStrikes+'/3 ocorrências antes da revisão de cargo.');if(sim.playerStrikes>=3){sim.playerStrikes=0;if(this.s.rank>0){this.s.rank--;this.s.victory=false;this.s.challenge=false;this.s.workflow=null;this.s.meeting=null;this.s.promotedDay=this.day;this.log('Revisão de desempenho: realocação para '+D.roles[this.s.rank]+'. Você pode reconstruir a carreira.');}else{this.s.receptionDuty=true;this.log('Revisão de desempenho: realocação para atendimento na recepção.');}}};
const previousFinish=Game.prototype.finishTask;Game.prototype.finishTask=function(){let a=this.s.activeTask;if(!a||a.mini.status==='playing')return false;let real=!a.practice,won=a.mini.status==='won';let result=previousFinish.call(this);if(real)this.recordPerformance(won);return result};
const previousBreak=Game.prototype.takeBreak;Game.prototype.takeBreak=function(){let sim=this.society(),chief=this.sectionChief(this.s.floor),minutes=sim.playerBreakDay===this.day?sim.playerBreakMinutes||0:0;let result=previousBreak.call(this);if(result){sim.playerBreakDay=this.day;sim.playerBreakMinutes=minutes+20;if(sim.playerBreakMinutes>40&&chief!==undefined&&this.location(D.npcs[chief])===this.s.floor){this.s.prestige=Math.max(0,this.s.prestige-3);this.log(D.npcs[chief].name+' registrou excesso de pausas: prestígio −3. As duas primeiras pausas são permitidas.');}}return result;};
const originalTasks=Object.getOwnPropertyDescriptor(Game.prototype,'tasks').get;
// The getter in careers.js is deliberately configurable for career extensions.
if(Object.getOwnPropertyDescriptor(Game.prototype,'tasks').configurable)Object.defineProperty(Game.prototype,'tasks',{configurable:true,get(){let tasks=originalTasks.call(this);if(!this.s.receptionDuty)return tasks;return tasks.map((t,i)=>({...t,name:['Receber visitantes','Conferir autorizações','Organizar solicitações','Passar o plantão'][i],floor:1,objectType:'reception',participants:i===3?[0]:[]}));}});
const previousPromote=Game.prototype.promote;Game.prototype.promote=function(){if(this.s.receptionDuty){if(!this.s.challenge||this.s.prestige<6)return false;this.s.receptionDuty=false;this.s.challenge=false;this.s.workflow=null;this.log('Retorno ao cargo de pleno após recuperação do desempenho.');return true;}return previousPromote.call(this)};
Game.noise=noise;
}if(typeof module!=='undefined')module.exports=install;else install(root.Game,root.DATA);})(typeof window!=='undefined'?window:globalThis);
