const {play}=require('./helpers.cjs');
const assert=require('node:assert/strict');const D=require('../data.js'),Game=require('../engine.js');
let checks=0;function test(name,fn){fn();checks++;console.log('PASS',name)}
test('70 NPCs / distribuição / centrais',()=>{assert.equal(D.npcs.length,70);assert.deepEqual(D.counts,D.floors.map((_,f)=>D.npcs.filter(n=>n.floor===f+1).length));assert.equal(D.npcs.filter(n=>n.central&&n.events.length>=3).length,14)});
test('elevador / acesso',()=>{let g=new Game();assert(g.go(2));assert(!g.go(7));g.s.invitations.push(7);assert(g.go(7))});
test('diálogo / anti-farming / preparo',()=>{let g=new Game();g.talk(0,'listen');assert.equal(g.s.relations[0],6);let t=g.s.time;assert(!g.talk(0,'listen'));assert.equal(g.s.time,t);g.talk(0,'advice');assert(g.s.prepared);g.talk(0,'support');assert(!g.s.supports.includes(0))});
test('tarefa / tempo / energia / fadiga',()=>{let g=new Game();play(g,'bug','segura');assert.equal(g.s.time,520);assert.equal(g.s.energy,93);assert(g.s.deliveries>0);assert(g.s.fatigue>=7&&g.s.fatigue<8);play(g,'bug','segura');assert(!play(g,'bug','segura'))});
test('agendas 18h, extras e executivo no próprio andar',()=>{let g=new Game();g.advance(600);assert.equal(g.location(D.npcs[1]),0);assert.equal(g.location(D.npcs[0]),1);let h=new Game();h.advance(240);assert.equal(h.location(D.npcs[60]),6)});
test('sono curto, recuperação, exaustão',()=>{let g=new Game();g.s.energy=20;g.s.fatigue=70;g.rest(4);assert(g.s.fatigue>70);g.rest(8);assert.equal(g.s.energy,100);assert(g.s.fatigue<30);g.s.fatigue=96;g.checkFatigue();assert(g.s.fatigue<95)});
test('inelegível / nova chance após derrota',()=>{let g=new Game();assert(!g.promote());g.advance(1440*3);assert.equal(g.s.losses,1);assert.equal(g.s.reopen,g.day+1);g.advance(1440);assert(g.requirements().find(r=>r.label==='Vaga disponível').ok)});
test('save e restore completos',()=>{let g=new Game('demo');g.talk(0,'help');play(g,'bug','segura');g.rest(8);let s=JSON.parse(JSON.stringify(g.s)),h=new Game(s.mode,s);assert.equal(h.s.deliveries,g.s.deliveries);assert.deepEqual(h.s.relations,g.s.relations);assert.equal(h.s.time,g.s.time)});
function campaign(mode){let g=new Game(mode),iterations=0;let supporters=[0,2,14,16];function morning(){g.nextMorning()}function ensure(minutes=60){if(g.hour+minutes>1070||g.s.energy<25||g.s.fatigue>55)morning();if(g.hour<510)g.advance(510-g.hour)}
while(g.s.rank<7&&iterations++<200){ensure();let r=D.requirements[g.s.rank];let ids=D.npcs.filter(n=>n.floor===Game.sponsorFloors[g.s.rank]).slice(0,r.s).map(n=>n.id);
for(let id of ids){let n=D.npcs[id];if(!g.access(n.floor))continue;if(g.s.relations[id]<Math.max(r.r,8+n.floor*2)||!g.s.supports.includes(id)){for(let action of ['listen','help','advice']){ensure(35);g.go(g.location(n));assert.equal(g.location(n),g.s.floor);g.talk(id,action)}if(g.s.relations[id]>=8+n.floor*2&&g.s.deliveries>=n.floor*2){ensure(20);g.go(n.floor);g.talk(id,'support')}}}
for(let k=0;k<4&&(g.s.deliveries<r.d||g.s.prestige<r.p||!g.s.challenge||(g.s.rank===6&&!g.s.strategic));k++){ensure(130);let t=g.tasks[Math.min(g.workflow.stage,3)];if(t.participants.length){for(let id of t.participants){let n=D.npcs[id],loc=g.location(n);if(loc&&g.go(loc))g.inviteMeeting(t.id,id);}g.advance(10);}if(!t){morning();continue}assert(play(g,t.id,t.best),JSON.stringify({task:t.id,reason:g.workReason(t.id,t.best),meeting:g.s.meeting,clock:g.clock()}))}
if(g.requirements().every(r=>r.ok)){assert(g.promote());console.log(mode,'promotion',D.roles[g.s.rank],'day',g.day)}else morning();}
assert.equal(g.s.rank,7,JSON.stringify(g.requirements()));return {mode,day:g.day,iterations,deliveries:g.s.deliveries,prestige:g.s.prestige,supports:g.s.supports.length,losses:g.s.losses}}
test('cadeia real normal até CEO sem injetar atributos',()=>{let result=campaign('normal');console.log(result);assert(result.day>=12&&result.day<200)});
test('cadeia real demonstração até CEO',()=>console.log(campaign('demo')));
console.log(checks+' grupos de testes passaram.');
