from pathlib import Path
p=Path('outputs/proximo-andar/engine.js');s=p.read_text().replace("const clamp=", "const clamp=")
s=s.replace("advance(m){let before", "advance(m,resting=false){if(!resting)this.s.fatigue=clamp(this.s.fatigue+m*.004,0,100);let before")
s=s.replace("for(const a of this.s.appointments)", "if(this.hour>=960&&this.day%3===0&&this.s.deliveries>8&&!this.s.memory[this.day+':plot']){this.s.memory[this.day+':plot']=true;let defender=this.s.supports.find(id=>this.s.relations[id]>=24);if(defender!==undefined)this.log(D.npcs[defender].name+' defendeu seu crédito na conversa dos rivais.');else{this.s.prestige=Math.max(0,this.s.prestige-2);this.log('Caio e Breno omitiram seu crédito. Prestígio −2. Quem ouviu a conversa na plataforma pode responder com evidência.');}}for(const a of this.s.appointments)")
s=s.replace("return f<=Math.min(7,this.s.rank+2)||this.s.invitations.includes(f)","return Number.isInteger(f)&&f>=1&&f<=7&&(f<=Math.min(7,this.s.rank+2)||this.s.invitations.includes(f)||this.influence>=D.influenceAccess[f-1])")
s=s.replace("if(n.floor>=6&&this.hour>=720&&this.hour<810)return 1;return n.floor", "if(n.floor>=6&&this.hour>=720&&this.hour<810)return 1;let visit=(D.visits[n.id]||[]).find(v=>this.hour>=v.from&&this.hour<v.to);return visit?visit.floor:n.floor")
start=s.index('workReason(');end=s.index('rest(hours)',start)
s=s[:start]+'''get workflow(){if(!this.s.workflow||this.s.workflow.day!==this.day)this.s.workflow={day:this.day,stage:0};return this.s.workflow}
workReason(id){if(this.s.activeTask)return 'Conclua a atividade em andamento.';const t=D.tasks.find(t=>t.id===id);if(!t)return 'Demanda não encontrada.';if(this.hour<480||this.hour>=1200)return 'Escritório fechado. Retorne às 8h.';if(this.s.rank<t.min)return 'Disponível a partir de '+D.roles[t.min]+'.';if(this.s.energy<t.cost)return 'Energia insuficiente. Faça uma pausa.';if((this.s.memory[this.day+':task:'+id]||0)>=2)return 'Tentativas de hoje encerradas. Escolha outra atividade.';if(id==='review'&&this.workflow.stage<1)return 'Primeiro: diagnosticar o bug da sprint.';if(id==='feature'&&this.workflow.stage<2)return 'Primeiro: concluir a revisão.';if(id==='strategy'&&this.workflow.stage<3)return 'Primeiro: implementar a entrega da sprint.';return '';}
work(id,approach){return this.startTask(id,approach)}
startTask(id,approach='segura',practice=false){if(this.s.activeTask)return false;let reason=practice?'':this.workReason(id);if(reason){this.log(reason);return false}let t=practice?{id,name:'Desafio do andar',minutes:20,cost:6,points:0,prestige:1}:D.tasks.find(t=>t.id===id);if(practice&&(this.hour<480||this.hour>=1200||this.s.energy<6||this.s.memory[this.day+':room:'+this.s.floor]))return false;const M=root.MINI||(typeof require!=='undefined'?require('./minigames.js'):null);let q=clamp(.65+(approach===t.best?.25:approach==='rápida'?-.12:.08)+(this.s.prepared?.15:0)-this.s.fatigue/220,.25,1.05),duration=Math.round(t.minutes*(approach==='rápida'?.7:approach==='colaborativa'?1.1:1)),overdue=this.hour+duration>1080;this.s.activeTask={id,approach,practice,floor:this.s.floor,q,overdue,points:t.points,prestige:t.prestige,name:t.name,mini:M.create(id,Math.floor(this.s.time)+this.s.rank*29,Math.min(3,1+Math.floor(this.s.rank/3)))};this.s.energy-=t.cost;this.s.fatigue=clamp(this.s.fatigue+(practice?4:D.workload[id])+(overdue?8:0),0,100);this.s.prepared=false;let key=practice?this.day+':room:'+this.s.floor:this.day+':task:'+id;this.s.memory[key]=(this.s.memory[key]||0)+1;this.advance(duration);this.log(t.name+': esforço reservado, energia −'+t.cost+'. Resolva a atividade para entregar.');return true}
miniMove(value){if(!this.s.activeTask)return false;const M=root.MINI||(typeof require!=='undefined'?require('./minigames.js'):null);M.act(this.s.activeTask.mini,value);if(this.s.activeTask.mini.status!=='playing')this.finishTask();return true}
finishTask(){let a=this.s.activeTask;if(!a||a.mini.status==='playing')return false;let won=a.mini.status==='won',q=clamp(a.q-a.mini.mistakes*.06,.25,1.05);if(won){this.s.deliveries+=a.points*q*this.cfg.reward;this.s.prestige+=a.prestige*q*this.cfg.reward;if(a.practice){let n=D.npcs.find(n=>n.floor===a.floor&&n.central);this.relation(n.id,3);this.s.prepared=true;}else{if(a.id==='bug')this.workflow.stage=Math.max(1,this.workflow.stage);if(a.id==='review')this.workflow.stage=Math.max(2,this.workflow.stage);if(a.id==='feature')this.workflow.stage=Math.max(3,this.workflow.stage);if(a.id==='strategy'&&q>=.65)this.s.strategic=true;if(q>=.65)this.s.challenge=true;}}if(a.overdue&&!a.practice)this.s.prestige=Math.max(0,this.s.prestige-1);this.s.lastTaskOutcome={won,name:a.name,quality:Math.round(q*100),deliveries:won?a.points*q*this.cfg.reward:0,practice:a.practice};this.log(won?a.name+': concluída, '+Math.round(q*100)+'% de qualidade.':a.name+': tentativa não concluída. Esforço consumido, sem recompensa.');this.s.activeTask=null;this.checkFatigue();return won}
abortTask(){if(!this.s.activeTask)return;this.s.activeTask.mini.status='lost';this.finishTask()}
takeBreak(){let key=this.day+':break';if((this.s.memory[key]||0)>=3||this.s.activeTask)return false;this.s.memory[key]=(this.s.memory[key]||0)+1;this.advance(20);this.s.energy=clamp(this.s.energy+16,0,100);this.s.fatigue=clamp(this.s.fatigue-12,0,100);this.log('Pausa no café: energia +16, fadiga −12.');return true}
observePlot(){if(this.s.floor!==3||this.hour<900||this.hour>=945)return false;this.s.evidence=true;this.advance(5);this.log('Você ouviu Caio e Breno articulando crédito. Evidência registrada para responder.');return true}
''' +s[end:]
s=s.replace('this.advance(hours*60);','this.advance(hours*60,true);').replace('this.advance(480-this.hour);','this.advance(480-this.hour,true);').replace('this.advance(1440-this.hour+480);','this.advance(1440-this.hour+480,true);')
p.write_text(s)
