from pathlib import Path
p=Path('outputs/proximo-andar/data.js');s=p.read_text();pos=s.index('const taskScenes=')
s=s[:pos]+'''const centralStories=[
 ['Bom te ver por aqui. Antes de procurar a sala mais importante, conheça quem faz este lugar funcionar.','Já ouvi seu nome nas equipes. Continue dividindo o crédito; as pessoas percebem.','Posso abrir algumas portas. Só não se esqueça de voltar para um café com a recepção.'],
 ['Sempre acontece alguma coisa por aqui. Você quer informação ou quer aparecer na reunião?','Tenho uma informação que pode ajudar. Mas faça sua parte quando a entrega sair.','Você cumpriu o combinado. Vou colocar seu nome na conversa certa.'],
 ['Eu gosto de orientar. Só cansa ver gente subir e esquecer quem ajudou no começo. Como você costuma trabalhar?','Você voltou para contar o resultado. Isso importa mais para mim do que um agradecimento apressado.','Já vi você ajudar sem tomar o lugar do colega. Quero defender sua candidatura.'],
 ['Estão olhando os resultados deste trimestre. Espero que você tenha algo convincente para mostrar.','Você está documentando tudo, pelo visto. Então vamos ser bem claros sobre quem entregou o quê.','Seu histórico está difícil de contestar. Posso reconhecer isso, mesmo disputando a mesma vaga.'],
 ['Passei a noite com alertas. Se você puder ajudar a remover uma causa de verdade, já melhora meu dia.','A equipe conseguiu dormir melhor depois daquela conversa. Vamos olhar os próximos riscos juntos?','Você entende que estabilidade também é uma entrega. Vou falar disso na avaliação.'],
 ['A próxima vaga deve abrir logo. Eu já estou escolhendo qual resultado vou apresentar.','Você entregou. Bom. Agora precisamos saber quem consegue repetir o resultado sem desgastar a equipe.','Somos concorrentes, mas eu reconheço um trabalho bem feito. Vamos competir com as regras claras.'],
 ['Tenho prazo apertado e uma equipe cansada. Preciso de uma proposta que caiba nos dois.','Você não prometeu o impossível. Isso me ajudou a negociar espaço para a equipe.','Quero ter mais líderes assim. Posso apoiar seu próximo passo com exemplos concretos.'],
 ['Engenharia quer qualidade, produto quer prazo. Antes de escolher um lado, me ajude a entender o problema.','A conversa ficou mais fácil quando você trouxe as pessoas para decidir juntas.','Você consegue transformar conflito em decisão. Eu vou lembrar disso na avaliação.'],
 ['Eu apoio boas ideias, mas preciso de evidências. Qual problema você resolveu, e quem participou?','Você trouxe números e reconheceu a equipe. Agora quero entender o que faria diferente.','Você aceita perguntas difíceis sem esconder os problemas. Tem meu apoio para liderar.'],
 ['Não há espaço para todo mundo na próxima rodada. Eu pretendo chegar preparado.','Você está ganhando visibilidade. Espero que as entregas acompanhem essa confiança toda.','Não vou fingir que somos amigos, mas seu trabalho merece uma avaliação justa.'],
 ['Talvez possamos conversar na semana que vem. Você consegue resumir o resultado em uma frase?','Agora eu entendi o impacto. Ainda preciso alinhar algumas coisas antes de assumir um compromisso.','Os resultados estão consistentes. Pode registrar meu apoio; vou sustentar essa posição.'],
 ['Quero saber como sua equipe termina o dia. Entregar tudo com todo mundo esgotado não resolve.','As pessoas me contaram que você escuta antes de distribuir trabalho. Continue assim.','Seu crescimento está criando espaço para outras pessoas. É por isso que vou apoiar você.'],
 ['Se crescermos hoje, quem paga a conta amanhã? Pessoas e recursos também precisam entrar no plano.','Gostei de ver sustentabilidade ligada a decisões concretas. Quais compromissos você consegue manter?','Você juntou resultado, responsabilidade e confiança. Vou levar seu nome ao conselho.'],
 ['Estou preparando minha sucessão. A cadeira precisa de alguém que una a empresa, não só suba os andares.','Seu nome chegou por pessoas de áreas diferentes. Agora quero ver como você decide sob pressão.','Você construiu algo que continua sem depender só de você. Está pronto para assumir a responsabilidade.']
];
npcs.filter(n=>n.central).forEach((n,i)=>n.events=centralStories[i]);
''' +s[pos:];p.write_text(s)
p=Path('outputs/proximo-andar/app.js');s=p.read_text();start=s.index('function newGame(');end=s.index('function resume()',start)
s=s[:start]+'''function newGame(mode){game=new Game(mode);world=new SCENE.World();save();dismissModal();conversation(D.npcs[0],'Bem-vindo à Nimbus! Eu sou a Lia. Seu crachá diz desenvolvedor pleno, mas aqui você vai conhecer bem mais do que código.',[{label:'Por onde eu começo?',action:'welcomeGuide()'},{label:'Vou conhecer o escritório. Até já!',action:'dismissModal()'}],'Sua primeira manhã · dia 1, 08h');refresh()}
function welcomeGuide(){conversation(D.npcs[0],'Converse com as pessoas e escolha uma entrega no seu caderno. A Helena, no segundo andar, pode orientar você. Quando chegar a hora de crescer, vai precisar de bons resultados e de gente que confie no seu trabalho.',[{label:'Certo. Vou dar uma volta.',action:'dismissModal()'}],'WASD/setas ou clique no chão: caminhar · E: interagir · T: entregas · V: vagas · Esc: pausa. Na saída você encerra o dia.')}
''' +s[end:]
s=s.replace("text='Você voltou! Eu estava pensando no que conversamos. '+n.context", "text='Você voltou! Eu estava pensando no que conversamos. '+(n.central?n.events[0]:'Vamos encontrar um tempo para conversar com calma?')")
p.write_text(s)
p=Path('outputs/proximo-andar/scene.js');s=p.read_text().replace('Math.sin(stride/5)','Math.sin(stride/11)');p.write_text(s)
p=Path('outputs/proximo-andar/index.html');s=p.read_text().replace('No mapa: <b>amarelo é você</b>. Aproxime-se de uma pessoa, elevador, mesa de trabalho ou saída e pressione E.', '<b>Amarelo é você.</b> Clique no chão ou use WASD/setas para caminhar. Perto de pessoas e objetos, pressione E.');p.write_text(s)
