from pathlib import Path
p=Path('outputs/proximo-andar/data.js');s=p.read_text().replace('const config={roles,','const balance={workdayStart:480,workdayEnd:1080,taskDailyLimit:2,forcedRestHours:8,extremeFatigue:95,socialFatigue:60,moveSpeed:180,saveInterval:10,rivalDailyProgress:34};\nconst config={balance,roles,');p.write_text(s)
p=Path('outputs/proximo-andar/engine.js');s=p.read_text().replace("if(!saved)this.log", "if(!this.s.rivals)this.s.rivals=[{id:15,name:'Caio Torres',progress:0},{id:31,name:'Breno Dias',progress:0},{id:55,name:'Otávio Sá',progress:0}];if(!saved)this.log")
s=s.replace('if(this.day>day){this.s.energy',"if(this.day>day){for(let rival of this.s.rivals)rival.progress=clamp(rival.progress+D.balance.rivalDailyProgress*(this.day-day),0,100);this.s.energy")
s=s.replace("this.s.reopen=0;this.s.vacancyUntil=this.day+3;this.log('Nova rodada", "this.s.reopen=0;this.s.vacancyUntil=this.day+3;for(let rival of this.s.rivals)rival.progress=0;this.log('Nova rodada")
s=s.replace("this.s.rank++;this.s.promotedDay", "this.s.rank++;for(let rival of this.s.rivals)rival.progress=0;this.s.promotedDay")
s=s.replace('this.s.fatigue>60','this.s.fatigue>D.balance.socialFatigue').replace('this.s.fatigue>=95','this.s.fatigue>=D.balance.extremeFatigue').replace('this.rest(8)}}','this.rest(D.balance.forcedRestHours)}}')
p.write_text(s)
p=Path('outputs/proximo-andar/app.js');s=p.read_text().replace('*180*dt','*D.balance.moveSpeed*dt').replace('saveTimer>10','saveTimer>D.balance.saveInterval')
s=s.replace("Uma derrota não retira entregas nem apoios.</p>","Uma derrota não retira entregas nem apoios.</p><p>Rivais ativos: '+s.rivals.map(r=>r.name+' '+r.progress+'%').join(' · ')+' (avanço limitado a 34 pontos/dia; só assumem no prazo).</p>")
s=s.replace('Math.floor(a.at%1440/60)', 'Math.floor(a.at%1440/60)').replace('String(a.at%60)', 'String(Math.floor(a.at%60))')
s=s.replace("ctx.fillText('ELEVADOR  '+floor,480,18);", "ctx.fillText('ELEVADOR  '+floor,480,18);")
s += "\n// Optional browser-native tools: normal UI actions, no hidden rewards or debug state.\nif(navigator.modelContext?.registerTool){for(const [name,description,type] of [['consultar_vagas','Abrir requisitos públicos da próxima promoção.','vacancies'],['consultar_tarefas','Abrir demandas e escolhas disponíveis.','tasks'],['consultar_agenda','Abrir compromissos e expediente.','agenda']])navigator.modelContext.registerTool({name,description,inputSchema:{type:'object',properties:{}},execute:async()=>{if(!game)return {content:[{type:'text',text:'Comece uma carreira no menu.'}]};panel(type);return {content:[{type:'text',text:'Painel aberto. O tempo está pausado.'}]}})}\n"
p.write_text(s)
p=Path('work/ui-test.cjs');s=p.read_text().replace('let sandbox={console,','let sandbox={console,navigator:{},');p.write_text(s)
