from pathlib import Path
p=Path('outputs/proximo-andar/app.js');s=p.read_text()
s=s.replace("let game=null,keys={},last=0,saveTimer=0,sound=false,audioCtx;", "let game=null,keys={},last=0,saveTimer=0,sound=false,audioCtx;let world=new SCENE.World(),dialogNpc=null,hudTimer=0,transitionUntil=0;const playerLook={skin:'#d69c72',hair:'#4c302b',shirt:'#e6b451',style:0,glasses:false,accessory:0};")
s=s.replace("function show(html){keys={};", "function show(html,kind=''){keys={};modal.className=kind;dialogNpc=kind==='conversation'?dialogNpc:null;")
s=s.replace('function dismissModal(){modal.close();', 'function dismissModal(){modal.close();dialogNpc=null;')
s=s.replace('game=new Game(mode);save();', 'game=new Game(mode);world=new SCENE.World();save();')
s=s.replace('game=new Game(s.mode,s);dismissModal()', 'game=new Game(s.mode,s);world=new SCENE.World();dismissModal()')
start=s.index("if(type==='tasks'){");end=s.index("\nif(type==='vacancies')",start)
s=s[:start]+'''if(type==='tasks'){html=head('Caderno de entregas')+'<p>Escolha uma situação para examinar. Você decide a abordagem antes de gastar tempo ou energia.</p><div class="cards tasklist">'+D.tasks.map(t=>{let reason=game.workReason(t.id);return '<div class="card"><span class="badge">'+(s.rank>=3?'COORDENAÇÃO':'EM EQUIPE')+' · '+t.minutes+' min base</span><h3>'+t.name+'</h3><p>'+t.desc+'</p><span class="badge">Energia −'+t.cost+' · prazo 18h</span><p class="'+(reason?'bad':'ok')+'">'+(reason||'Disponível · '+(s.memory[game.day+':task:'+t.id]||0)+'/2 feitas hoje')+'</p>'+button('Examinar situação',"taskScene('"+t.id+"')",!!reason)+'</div>'}).join('')+'</div><div class="actions">'+button('Encerrar o dia','restMenu()')+'</div>'}
''' +s[end:]
start=s.index('function doWork(');end=s.index('function apply()',start)
s=s[:start]+'''function conversation(n,text,choices,feedback=''){dialogNpc=n.id;show('<div class="conversation-inner"><div class="portrait-frame"><canvas id="portrait" width="160" height="180" aria-label="Retrato de '+n.name+'"></canvas><span>'+n.name+'</span></div><div class="speech"><div class="speaker"><div><small>'+n.job+'</small><h2>'+n.name+'</h2></div><button onclick="dismissModal()" aria-label="Encerrar conversa">✕</button></div><p class="spoken">'+text+'</p>'+(feedback?'<p class="consequence">'+feedback+'</p>':'')+'<div class="choices">'+choices.map((c,i)=>button('<kbd>'+(i+1)+'</kbd> '+c.label,c.action,c.disabled)).join('')+'</div><small class="dialog-help">1–4 escolher · Esc sair · tempo pausado</small></div></div>','conversation');SCENE.portrait($('#portrait'),n)}
function taskScene(id){const t=D.tasks.find(t=>t.id===id),scene=D.taskScenes[id],n=D.npcs[[14,14,0,30,42,66][D.tasks.indexOf(t)]];conversation(n,scene.intro,['segura','colaborativa','rápida'].map((a,i)=>({label:scene.choices[i]+' <span class="choice-cost">'+Math.round(t.minutes*(a==='rápida'?.7:a==='colaborativa'?1.1:1))+' min</span>',action:"doWork('"+id+"','"+a+"')"})), 'Energia −'+t.cost+' · prazo 18h · recompensa base '+t.points*game.cfg.reward+' entregas e '+t.prestige*game.cfg.reward+' prestígio. '+(game.s.prepared?'Você tem orientação: +15% de qualidade.':'Peça orientação para se preparar.')+(game.hour>=1080?' Hora extra: mais fadiga e prazo excedido.':''))}
function doWork(id,a){let reason=game.workReason(id);if(reason){show(head('Agora não é possível')+'<p>'+reason+'</p>'+button('Voltar às demandas',"panel('tasks')")+button('Encerrar o dia','restMenu()'));return}const t=D.tasks.find(t=>t.id===id),before=game.s.deliveries;act(()=>game.work(id,a));const n=D.npcs[[14,14,0,30,42,66][D.tasks.indexOf(t)]];conversation(n,D.taskScenes[id].reply,[{label:'Vamos ver o que mais precisa de atenção.',action:"panel('tasks')"},{label:'Voltar ao escritório.',action:'dismissModal()'}],game.s.logs.find(l=>l.includes(t.name+':'))||('Entregas +'+(game.s.deliveries-before).toFixed(1)));transitionUntil=performance.now()+350}
''' +s[end:]
start=s.index('function talk(');end=s.index('function elevator()',start)
s=s[:start]+'''function talk(id){let n=D.npcs[id],r=game.s.relations[id],stage=r<12?0:r<24?1:2;let text=n.central?n.events[stage]:['Ainda estou pegando o ritmo de hoje. Você também está com bastante coisa para fazer?','Bom te ver de novo. Aquela ajuda fez diferença para mim.','Senta aqui um minuto. Quero saber como anda sua próxima entrega.'][stage];let met=Object.keys(game.s.memory).some(k=>k.includes(':'+id+':'));if(met&&stage===0)text='Você voltou! Eu estava pensando no que conversamos. '+n.context;conversation(n,text,[{label:'Como anda seu interesse por '+n.interest+'?',action:"dialogAction("+id+",'listen')"},{label:'Posso ajudar com alguma coisa?',action:"dialogAction("+id+",'help')"},{label:'Queria ouvir sua opinião sobre minha entrega.',action:"dialogAction("+id+",'advice')"},{label:'Tem outra coisa que queria conversar…',action:'moreTalk('+id+')'}],(world.people.get(id)?.activity||'no escritório')+' · '+(game.s.supports.includes(id)?'Apoia sua candidatura':r>=20?'Confiança construída':r>0?'Conhecendo você':'Primeira aproximação'))}
function moreTalk(id){const n=D.npcs[id];conversation(n,'Pode falar. O que você tem em mente?',[{label:'Quero compartilhar os resultados da equipe.',action:"dialogAction("+id+",'share')"},{label:'Você apoiaria minha candidatura?',action:"dialogAction("+id+",'support')"},{label:'Vamos tomar um café daqui a uma hora?',action:"dialogAction("+id+",'coffee')"},{label:'Preciso esclarecer a autoria daquela entrega.',action:"dialogAction("+id+",'defend')"}], 'Apoio requer relação '+(8+n.floor*2)+' e '+n.floor*2+' entregas. Você tem '+game.s.relations[id]+' de relação. Pedir cedo pode prejudicar a confiança.')}
function dialogAction(id,a){const n=D.npcs[id],before=game.s.relations[id],supported=game.s.supports.includes(id),evidence=game.s.evidence;let used=game.talk(id,a);save();refresh();let delta=game.s.relations[id]-before,reply='';if(!used)reply='A gente já conversou sobre isso hoje. Vamos retomar depois de algo novo acontecer?';else if(a==='listen')reply={café:'Descobri uma mistura nova. Um dia trago para a equipe experimentar.',livros:'Estou lendo um livro que me fez repensar como escuto as pessoas.',música:'Tenho uma playlist para os dias difíceis. Posso te mostrar no intervalo.',jardinagem:'Minha planta finalmente deu uma folha nova. Paciência faz diferença.',corrida:'Hoje consegui correr antes do trabalho. Ajuda a organizar as ideias.',cinema:'Vi um filme que ficou na minha cabeça. Quero discutir o final com alguém.',jogos:'Gosto quando um jogo me deixa resolver as coisas do meu jeito.',sustentabilidade:'Quero que nossas escolhas durem mais do que o próximo trimestre.'}[n.interest]+' E você, consegue desligar um pouco?';else if(a==='help')reply=n.personality==='hostil'?'Tudo bem. Vamos registrar quem fez o quê antes de começar.':'Sim. Preciso de uma segunda opinião. Obrigado por reservar esse tempo — vou lembrar de dividir o crédito.';else if(a==='advice')reply='Escolha um problema pequeno, entenda a causa e peça revisão antes de entregar. Você não precisa provar tudo sozinho.';else if(a==='share')reply=delta>0?'Você trouxe resultados e reconheceu quem participou. É esse tipo de trabalho que eu quero ver crescer.':'Ainda preciso ver algo concreto. Volte com uma entrega e a gente conversa melhor.';else if(a==='support')reply=game.s.supports.includes(id)?'Sim. Você pode contar comigo na avaliação. Também vou apresentar você às pessoas do próximo andar.':'Ainda não consigo assumir esse compromisso. Vamos trabalhar juntos um pouco mais antes?';else if(a==='coffee')reply='Combinado. Daqui a uma hora! Anote na agenda para não passar batido.';else if(a==='defend')reply=evidence?'O registro deixa claro quem participou. Vou ajudar a esclarecer isso.':'Sem um registro, eu não consigo confirmar essa história. Vamos procurar evidências primeiro.';conversation(n,reply,[{label:'Quero te perguntar mais uma coisa.',action:'talk('+id+')'},{label:'Obrigado. Nos vemos pelo escritório.',action:'dismissModal()'}],used?'Relação '+(delta>=0?'+':'')+delta+' · '+(a==='help'?'30 minutos dedicados à ajuda.':a==='advice'?'Próxima entrega preparada.':'15 minutos de conversa.'):'Sem custo de tempo ou ganho repetido.')}
''' +s[end:]
s=s.replace('function travel(f){act(()=>game.go(f));dismissModal()}',"function travel(f){act(()=>game.go(f));world=new SCENE.World();transitionUntil=performance.now()+450;dismissModal()}")
start=s.index('function restMenu()');end=s.index('function pause()',start)
s=s[:start]+'''function restMenu(){show(head('Por hoje, é isso.')+'<p class="intro">Amanhã tem mais. Escolha quanto vai dormir; se acordar antes da abertura, o tempo pessoal passa até as 8h.</p><p>Você recupera apenas pelas horas dormidas. Menos de 7h acumula fadiga. Entregas encerram às 20h.</p><label for="hours">Horas de sono</label> <select id="hours">'+[2,4,6,8,10].map(h=>'<option '+(h===8?'selected':'')+'>'+h+'</option>').join('')+'</select><div class="actions">'+button('Dormir e retornar no horário útil','sleepChosen()',false,true)+button('Ainda tenho algo para fazer','dismissModal()')+'</div>')}
function sleepChosen(){act(()=>game.endDay(Number($('#hours').value)));world=new SCENE.World();transitionUntil=performance.now()+600;dismissModal();show(head('Um novo expediente')+'<p class="intro">Dia '+game.day+' · '+game.clock()+'. As portas da Nimbus estão abertas.</p><p>Energia '+Math.round(game.s.energy)+' · fadiga '+Math.round(game.s.fatigue)+'. '+(game.s.fatigue>60?'Hoje vale reduzir o ritmo e buscar orientação.':'Procure sua equipe e escolha a prioridade do dia.')+'</p>'+button('Entrar','dismissModal()',false,true))}
function sleepMorning(){sleepChosen()}
''' +s[end:]
start=s.index('function npcPos(');end=s.index("window.addEventListener('keydown'",start)
s=s[:start]+'''function npcPos(n){return world.people.get(n.id)||SCENE.home(n)}
function near(){if(!game)return null;let {x,y}=game.s;if(Math.hypot(x-480,y-85)<85)return {type:'elevator',label:'E · Elevador'};if(y>515&&Math.abs(x-480)<115)return {type:'exit',label:'E · Encerrar o dia'};let closest=null,distance=54;for(let n of D.npcs){if(game.location(n)===game.s.floor){let p=npcPos(n),d=Math.hypot(x-p.x,y-p.y);if(d<distance){distance=d;closest={type:'npc',id:n.id,label:'E · '+n.name}}}}if(closest)return closest;if(desks.some(d=>Math.hypot(x-(d.x+d.w/2),y-(d.y+d.h/2))<90))return {type:'desk',label:'E · Examinar entregas'};return null}
function interact(){if(!game||modal.open)return;let n=near();if(!n)return;if(n.type==='elevator')elevator();if(n.type==='exit')restMenu();if(n.type==='npc')talk(n.id);if(n.type==='desk')panel('tasks')}
function blocked(x,y){return SCENE.blocked(x,y)}
function draw(){let floor=game?game.s.floor:1;ctx.imageSmoothingEnabled=false;SCENE.background(ctx,floor,game?game.hour:600);if(game){world.update(game,0,dialogNpc);let target=near();let list=[...world.people.values()].map(p=>({...p,n:D.npcs[p.id]}));list.push({...game.s,player:true});list.sort((a,b)=>a.y-b.y).forEach(p=>{let active=p.player||target?.id===p.id;SCENE.sprite(ctx,p.x,p.y,p.player?playerLook:p.n.appearance,p.facing,p.stride,p.moving,active);if(active&&!p.player){ctx.font='bold 13px system-ui';ctx.textAlign='center';let label=p.n.name;ctx.fillStyle='#203744';ctx.fillRect(p.x-75,p.y-61,150,20);ctx.fillStyle='#fff0c5';ctx.fillText(label,p.x,p.y-46)}if(p.player){ctx.fillStyle='#fff0a4';ctx.beginPath();ctx.moveTo(p.x,p.y-43);ctx.lineTo(p.x-4,p.y-49);ctx.lineTo(p.x+4,p.y-49);ctx.fill()}});$('#hint').textContent=target?.label||(game.hour>=1080?'Horas extras · entregas até 20h. E na saída para encerrar.':'WASD / setas mover · aproxime-se e pressione E');if(transitionUntil>performance.now()){ctx.fillStyle='rgba(20,34,46,'+Math.min(.8,(transitionUntil-performance.now())/600)+')';ctx.fillRect(0,0,960,600)}}}
function frame(t){let dt=Math.min(Math.max((t-last)/1000,0),.05);last=t;if(game&&!modal.open&&!document.hidden){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);SCENE.move(game.s,dx,dy,dt,D.balance.moveSpeed);game.advance(dt);world.update(game,dt);saveTimer+=dt;hudTimer+=dt;if(saveTimer>D.balance.saveInterval){save();saveTimer=0}if(hudTimer>.25){refresh();hudTimer=0}}else if(game)game.s.moving=false;draw();requestAnimationFrame(frame)}
''' +s[end:]
s=s.replace("if(modal.open)return;keys[e.key]=true;", "if(modal.open){if(modal.className==='conversation'&&/^[1-4]$/.test(e.key)){let choice=document.querySelectorAll('.choices button')[Number(e.key)-1];if(choice&&!choice.disabled)choice.click()}return}keys[e.key.length===1?e.key.toLowerCase():e.key]=true;")
s=s.replace("e=>keys[e.key]=false", "e=>keys[e.key.length===1?e.key.toLowerCase():e.key]=false")
p.write_text(s)
p=Path('outputs/proximo-andar/index.html');s=p.read_text().replace('<script src="app.js">','<script src="scene.js"></script><script src="app.js">');p.write_text(s)
p=Path('outputs/proximo-andar/engine.js');s=p.read_text().replace('this.rest(D.balance.forcedRestHours)}}','this.endDay(D.balance.forcedRestHours)}}');p.write_text(s)
